import os

files_data = {
    'src/data/blog-content/best-car-tint-jeddah-2026.ts': {
        "textEn: 'Car Tinting Service in Jeddah — Prices and Specs 2026'": "text: 'خدمة تظليل سيارات بجدة — أسعار ومواصفات 2026'",
        "textEn: 'Authorized Johnson Dealer in Jeddah'": "text: 'وكيل جونسون المعتمد في جدة'",
        "textEn: 'Authorized 3M Dealer — Crystalline and Ceramic IR'": "text: 'وكيل 3M المعتمد — Crystalline و Ceramic IR'",
        "quickAnswerEn: 'The best tint shop in Jeddah is an authorized dealer of a global brand (Johnson, 3M, or XPEL), has a closed air-conditioned workshop, uses a computer plotter for cutting, and provides a tax invoice + a registered electronic warranty. Expect to pay 1,500 to 3,500 SAR for authentic nano-ceramic — any price under 1,200 SAR for a full sedan means commercial film.'": "quickAnswer: 'أفضل محل تظليل في جدة هو المعتمد من ماركة عالمية (Johnson أو 3M أو XPEL)، يملك ورشة مغلقة مكيفة، يستخدم قص كمبيوتر (Plotter)، ويقدم فاتورة ضريبية + ضمان إلكتروني مسجل. توقع دفع 1,500 إلى 3,500 ريال لنانو سيراميك أصلي — أي سعر أقل من 1,200 ريال لسيدان كاملة يعني فيلم تجاري.'",
        "introEn: 'Choosing a tint shop in Jeddah is truly confusing — there are dozens of shops and prices range from 200 to 4,000 SAR for the same car size. The real difference isn\\'t just price, but film type, installation environment, and technician experience. In this guide, we give you the criteria for choosing a professional shop based on field experience in the Jeddah market.'": "intro: 'اختيار محل تظليل في جدة عملية محيرة فعلاً — المحلات بالعشرات والأسعار تتراوح بين 200 و 4,000 ريال لنفس حجم السيارة. الفارق الحقيقي ليس في السعر فقط، بل في نوع الفيلم، بيئة التركيب، وخبرة الفني. في هذا الدليل، نضع بين يديك معايير اختيار المحل المحترف مبنية على خبرة ميدانية في سوق جدة.'",
        "headersEn: ['Tint Type', 'Price Range (Sedan)', 'Lifespan', 'Heat Rejection (IR)']": "headers: ['نوع التظليل', 'نطاق السعر (سيدان)', 'العمر الافتراضي', 'حجب الحرارة (IR)']",
        "rowsEn: [\n        ['Regular Dyed', '200 - 500 SAR', '6 months - 1 year', '20% - 30%'],\n        ['Advanced Carbon', '800 - 1,500 SAR', '5 - 7 years', '75% - 85%'],\n        ['Nano-Ceramic', '1,500 - 3,200 SAR', '10 - 15 years', '90% - 97%'],\n        ['3M Crystalline (Front only)', '700 - 1,500 SAR', 'Lifetime of car', '97%'],\n        ['Johnson Supreme IR', '1,800 - 3,500 SAR', 'Lifetime of car', '97%'],\n        ['XPEL PRIME XR+', '2,500 - 4,000 SAR', '10+ years', '98%']\n      ]": "rows: [\n        ['تظليل مصبوغ عادي (Dyed)', '200 - 500 ر.س', '6 أشهر - سنة', '20% - 30%'],\n        ['كربوني متقدم (Carbon)', '800 - 1,500 ر.س', '5 - 7 سنوات', '75% - 85%'],\n        ['نانو سيراميك (Ceramic)', '1,500 - 3,200 ر.س', '10 - 15 سنة', '90% - 97%'],\n        ['3M Crystalline (أمامي فقط)', '700 - 1,500 ر.س', 'عمر السيارة', '97%'],\n        ['Johnson Supreme IR', '1,800 - 3,500 ر.س', 'عمر السيارة', '97%'],\n        ['XPEL PRIME XR+', '2,500 - 4,000 ر.س', '10+ سنوات', '98%'],\n      ]",
        "headingEn: '5 Golden Rules to Choose a Tint Shop'": "heading: '5 معايير ذهبية لاختيار محل التظليل'",
        "bodyEn: 'First: Official agency for a global brand (Johnson, 3M, LLumar, XPEL) — not just a seller but an authorized dealer with a certificate in shop. Second: Closed, AC workshop — outdoor tinting guarantees dust and bubbles. Third: Computer plotter — manual blade cutting leaves gaps and scratches glass. Fourth: Tax invoice + e-warranty via chassis number — no invoice means worthless warranty. Fifth: Certified technician by IWFA or direct factory training.'": "body: 'أولاً: وكالة رسمية من ماركة عالمية (Johnson أو 3M أو LLumar أو XPEL) — ليس مجرد بائع للفيلم بل وكيل معتمد بشهادة تُعلَّق في المحل. ثانياً: ورشة مغلقة ومكيفة — التظليل في العراء يعني غباراً وفقاعات مضمونة تحت الفيلم. ثالثاً: قص كمبيوتر (Plotter) — القص اليدوي بالشفرة يترك فراغات دقيقة ويخدش الزجاج. رابعاً: فاتورة ضريبية + ضمان إلكتروني مسجل برقم الشاصي — بدون فاتورة الضمان لا يساوي الحبر الذي كُتب به. خامساً: فني معتمد بشهادة IWFA أو تدريب مباشر من المصنع.'",
        "headingEn: 'Signs of a Reliable vs. Fake Shop'": "heading: 'علامات المحل الموثوق مقابل المقلد'",
        "bodyEn: 'A reliable shop displays the original certificate clearly at reception. They explain differences honestly and don\\'t push the most expensive without technical justification. They measure VLT with a Tint Meter in front of you post-installation. They provide printed care instructions. They offer free annual checkups. Fake shops use fake marketing names like \"SuperNano\" or \"Ceramic Pro Tint\" — names non-existent in any global company database.'": "body: 'المحل الموثوق يعرض شهادة الوكالة الأصلية بوضوح في الاستقبال (وليس فقط ادعاءات شفهية). يشرح لك الفرق بين الأنواع بصراحة ولا يدفعك مباشرة للأغلى دون تبرير تقني. يقيس نسبة الشفافية (VLT) بجهاز Tint Meter أمامك بعد التركيب. يقدم لك ورقة تعليمات العناية المطبوعة (متى تنزّل الزجاج، كيف تنظف). يوفر فحصاً سنوياً مجانياً للفيلم. أما المحل المقلد فيستخدم أسماء تسويقية وهمية مثل \"SuperNano\" أو \"Ceramic Pro Tint\" — أسماء لا وجود لها في قاعدة بيانات أي شركة عالمية.'",
        "headingEn: 'Post-Installation: What to Expect in the First 30 Days?'": "heading: 'بعد التركيب: ماذا تتوقع في أول 30 يوماً؟'",
        "bodyEn: 'First 48 hours: Do not roll down windows at all — adhesive hasn\\'t dried due to Jeddah humidity (60-80%). First 1-3 weeks: Small bubbles are completely normal and will disappear as adhesive dries. First month: Don\\'t stick anything on tinted glass. After a month: Use ammonia-free cleaner exclusively with soft microfiber cloth. Pro tip: Tint between Sep-Nov when humidity drops, drying in 3-4 days instead of a week in summer.'": "body: 'أول 48 ساعة: لا تنزّل الزجاج إطلاقاً — اللاصق لم يجف بعد بسبب رطوبة جدة (60-80%). أول 1-3 أسابيع: ظهور فقاعات صغيرة أمر طبيعي تماماً وستختفي وحدها مع جفاف اللاصق. أول شهر: لا تلصق أي شيء على الزجاج المظلل. بعد شهر: استخدم منظفاً خالياً من الأمونيا حصرياً مع قماش مايكروفايبر ناعم. الأفضل: اختر وقت التركيب بين سبتمبر ونوفمبر حيث تقل الرطوبة ويجف الفيلم خلال 3-4 أيام بدلاً من أسبوع كامل في الصيف.'",
        "authorEn: 'Eng. Ahmed Salem'": "author: 'م. أحمد سالم'",
        "roleEn: 'Thermal Insulation Consultant — AzelCore'": "role: 'مستشار العزل الحراري — عزل كور'",
        "textEn: 'My rule for every customer: If the shop can\\'t show you an IR Meter and test the film in front of you, they aren\\'t confident in their product. Every pro shop owns this as a core sales tool. The difference between 1,500 and 400 SAR is literally the difference between 10 years of comfort and 3 months of regret.'": "text: 'القاعدة التي أقولها لكل عميل: لو المحل ما يقدر يُريك جهاز IR Meter ويختبر الفيلم أمامك قبل وبعد التركيب، فهو ليس واثقاً من جودة منتجه. كل محل محترف يملك هذا الجهاز ويعتبره أداة بيع أساسية. الفرق بين 1,500 و 400 ريال هو حرفياً الفرق بين 10 سنوات راحة و 3 أشهر ندم.'",
        "qEn: 'Is there a difference between tint shops in north and south Jeddah?'": "q: 'هل يوجد فرق بين محلات التظليل في شمال وجنوب جدة؟'",
        "aEn: 'The difference isn\\'t geographical, it\\'s in accreditations. Look for a shop with an official factory agency certificate regardless of location. AzelCore Center serves all Jeddah districts.'": "a: 'الفرق ليس جغرافياً بل في الاعتمادات. ابحث عن المحل الحاصل على شهادة وكالة رسمية من المصنع بغض النظر عن موقعه. مركز عزل كور يخدم جميع أحياء جدة.'",
        "qEn: 'Why do nano-ceramic prices vary from 1,500 to 3,500 SAR?'": "q: 'لماذا أسعار النانو سيراميك تتفاوت بين 1,500 و 3,500 ريال؟'",
        "aEn: 'The difference lies in the production line (model). For example, Johnson Supreme IR is pricier than Johnson Optik because its heat rejection (TSER) is higher. Car size also matters — tinting an SUV is about 20-30% more expensive than a sedan.'": "a: 'الفرق في خط الإنتاج (الموديل). مثلاً Johnson Supreme IR أعلى سعراً من Johnson Optik لأن نسبة حجب الحرارة (TSER) أعلى. أيضاً حجم السيارة يؤثر — تظليل SUV أغلى من سيدان بحوالي 20-30%.'",
        "qEn: 'How long does tinting a full car take?'": "q: 'كم يستغرق تركيب التظليل لسيارة كاملة؟'",
        "aEn: 'In a professional shop with computer plotter: 2-3 hours for sedan, 3-4 hours for SUV. Shops that finish in under an hour often use fast manual cutting which affects installation and edge quality.'": "a: 'في ورشة احترافية بقص كمبيوتر: 2-3 ساعات لسيدان، 3-4 ساعات لـ SUV. المحلات التي تنهي العمل في أقل من ساعة غالباً تستخدم قصاً يدوياً سريعاً يؤثر على جودة التركيب والأطراف.'",
        "warningEn: 'A shop without commercial registration or tax invoice offers no real warranty. If the film fails after a month, you have no legal basis to claim. The difference between 1,500 and 400 SAR = difference between long-term investment and guaranteed loss.'": "warning: 'محل بدون سجل تجاري ولا فاتورة ضريبية لا يقدم ضماناً حقيقياً. إذا تلف الفيلم بعد شهر، لا تملك أي مستند قانوني للمطالبة. الفرق بين 1,500 و 400 ريال = فرق بين استثمار طويل الأمد وخسارة مؤكدة.'",
        "ctaEn: 'Don\\'t risk your car. Book authentic tinting with a certified e-warranty at AzelCore Center in Jeddah.'": "cta: 'لا تغامر بسيارتك. احجز تظليلاً أصلياً مع ضمان إلكتروني معتمد في مركز عزل كور بجدة.'"
    },
    'src/data/blog-content/how-to-spot-fake-tint.ts': {
        "textEn: 'Install Authentic Nano-Ceramic Tint in Jeddah'": "text: 'تركيب تظليل نانو سيراميك أصلي بجدة'",
        "textEn: 'Verify Our Accreditation with US Johnson Window Films'": "text: 'تحقق من اعتمادنا لدى شركة جونسون الأمريكية'",
        "textEn: 'Authorized 3M Dealer — Original Films with Factory Warranty'": "text: 'وكيل 3M المعتمد — أفلام أصلية بضمان المصنع'",
        "quickAnswerEn: 'To spot fake tint: Request an insulation test with an IR Meter (original rejects over 90%), check for the brand\\'s watermark on the film, demand a certified e-invoice with chassis number for warranty, and avoid any \"nano-ceramic\" sold for under 1,200 SAR for a full car.'": "quickAnswer: 'لاكتشاف التظليل المقلد: اطلب قياس العزل بجهاز IR Meter (الأصلي يعزل فوق 90%)، تأكد من وجود شعار العلامة التجارية مائياً على الفيلم، اطلب الفاتورة الإلكترونية المعتمدة برقم هيكل السيارة للضمان، وتجنب أي \"نانو سيراميك\" يُباع بأقل من 1,200 ريال لسيارة كاملة.'",
        "introEn: 'Jeddah\\'s tint market is flooded with commercial fake films sold as \"nano-ceramic\" at tempting prices (300 to 500 SAR). The result? The film turns purple in months, heat easily penetrates the glass, and your rear window might deform when attempting to remove the cheap glue. In this guide, we provide 5 definitive engineering ways to spot fake tint before paying a single Riyal.'": "intro: 'سوق التظليل في جدة يغص بالأفلام التجارية المقلدة التي تُباع تحت مسمى \"نانو سيراميك\" بأسعار تبدو مغرية (300 إلى 500 ريال). النتيجة؟ الفيلم يتحول للون البنفسجي خلال أشهر، الحرارة تخترق الزجاج بسهولة، وقد يتشوه زجاجك الخلفي عند محاولة إزالة الغراء الرديء. في هذا الدليل، نضع بين يديك 5 طرق هندسية وقطعية لكشف التظليل المقلد قبل أن تدفع ريالاً واحداً.'",
        "headersEn: ['Comparison Point', 'Authentic Nano-Ceramic', 'Fake Commercial Tint']": "headers: ['وجه المقارنة', 'النانو سيراميك الأصلي', 'التظليل التجاري المقلد']",
        "rowsEn: [\n        ['IR Meter Test', 'Rejects 90% to 97% of heat', 'Rejects only 20% to 40%'],\n        ['Watermark', 'Company logo printed clearly on the roll', 'No logo, or fake logo with spelling errors'],\n        ['Glue Smell at Install', 'Odorless or very light smell', 'Pungent chemical smell (causes headaches)'],\n        ['Color Change After 6 Mos', 'Retains its deep black or charcoal color', 'Fades or turns dark purple'],\n        ['Fair Market Price (Sedan)', '1,500 to 3,000 SAR', '300 to 800 SAR max']\n      ]": "rows: [\n        ['اختبار جهاز قياس الحرارة (IR Meter)', 'يحجب 90% إلى 97% من الحرارة', 'يحجب 20% إلى 40% فقط'],\n        ['العلامة المائية (Watermark)', 'شعار الشركة مطبوع بوضوح على الرول', 'لا يوجد أي شعار، أو شعار مقلد به أخطاء إملائية'],\n        ['رائحة الغراء وقت التركيب', 'بدون رائحة أو رائحة خفيفة جداً', 'رائحة كيميائية نفاذة (تسبب الصداع)'],\n        ['تغير اللون بعد 6 أشهر', 'يحتفظ بلونه الأسود أو الفحمي العميق', 'يبهت أو يتحول للون البنفسجي الداكن'],\n        ['السعر العادل في السوق (سيدان)', '1,500 إلى 3,000 ريال', '300 إلى 800 ريال كحد أقصى']\n      ]",
        "headingEn: '1. Practical Test with IR Meter (The Gold Standard)'": "heading: '1. الفحص العملي بجهاز IR Meter (المعيار الذهبي)'",
        "bodyEn: 'Words don\\'t reject heat, numbers do. Fake tint relies on \"darkening glass\" to reduce sun glare, but fails completely to stop \"Infrared\" (IR) rays carrying actual heat. Ask the center to use an IR Transmission Meter. Put the original film (like Johnson Supreme) and you\\'ll see rejection exceed 95%. A commercial dyed film won\\'t break 40% even if very dark (03).'": "body: 'الكلمات لا تعزل الحرارة، الأرقام تفعل. التظليل المقلد يعتمد على \"تعتيم الزجاج\" لتقليل وهج الشمس، لكنه يفشل تماماً في إيقاف \"الأشعة تحت الحمراء\" (IR) التي تحمل الحرارة الفعلية. اطلب من المركز استخدام جهاز IR Transmission Meter. ضع الفيلم الأصلي (مثل Johnson Supreme) في الجهاز وسترى نسبة الرفض تتجاوز 95%. الفيلم التجاري المصبوغ لن يتجاوز حاجز الـ 40% حتى لو كان داكناً جداً (03).'",
        "headingEn: '2. Absence of Electronic Warranty (e-Warranty)'": "heading: '2. غياب شهادة الضمان الإلكترونية (e-Warranty)'",
        "bodyEn: 'Global companies don\\'t recognize \"handwritten paper invoices\" as official warranties. Original films come with an e-warranty registration linked to the car\\'s VIN in the parent company\\'s database (like 3M or Johnson site). If the center can\\'t provide a link to verify your car on the manufacturer\\'s site, you\\'re buying 100% fake film.'": "body: 'الشركات العالمية لا تعتمد \"الفواتير الورقية المكتوبة بخط اليد\" كضمان رسمي. الفيلم الأصلي يأتي معه تسجيل ضمان إلكتروني مرتبط برقم شاصي السيارة (VIN) في قاعدة بيانات الشركة الأم (مثل موقع 3M أو Johnson). إذا لم يتمكن المركز من تزويدك برابط للتحقق من سيارتك على موقع الشركة المصنعة، فأنت تشتري فيلماً مقلداً بنسبة 100%.'",
        "headingEn: '3. Night Vision Test (Haze and Refraction)'": "heading: '3. اختبار الرؤية الليلية (الضبابية والانكسار)'",
        "bodyEn: 'Original nano-ceramic films are made with advanced optical layering ensuring clear inside-out vision (Low Internal Reflectivity). Conversely, fake tint relies on cheap dyes causing severe interior dashboard reflection on glass at night (making it a mirror), weakening road vision and posing real danger while driving.'": "body: 'أفلام النانو سيراميك الأصلية تُصنع بتقنية طبقات بصرية متقدمة تضمن صفاء الرؤية من الداخل للخارج (Low Internal Reflectivity). في المقابل، التظليل المقلد يعتمد على صبغات رخيصة تسبب انعكاساً شديداً للديكور الداخلي على الزجاج ليلاً (كأن الزجاج أصبح مرآة)، مما يضعف رؤيتك للطريق ويشكل خطراً حقيقياً أثناء القيادة.'",
        "authorEn: 'Eng. Ahmed Salem'": "author: 'م. أحمد سالم'",
        "roleEn: 'Thermal Insulation Expert'": "role: 'خبير العزل الحراري'",
        "textEn: 'The biggest mistake I see daily is a customer paying 500 SAR for fake tint, then forced to pay 200 SAR to remove it after rear glass damage, then 2000 SAR to install the original. Investing in original from the start is true savings. Always verify the authorized dealer certificate is hung in the center.'": "text: 'الخطأ الأكبر الذي أراه يومياً هو عميل دفع 500 ريال في تظليل مقلد، ثم اضطر لدفع 200 ريال لإزالته بعد أن تضرر الزجاج الخلفي، ثم دفع 2000 ريال لتركيب الأصلي. الاستثمار في الأصلي من البداية هو التوفير الحقيقي. تأكد دائماً من وجود شهادة الوكيل المعتمد معلقة في المركز.'",
        "qEn: 'Can fake tint be spotted after installation?'": "q: 'هل يمكن كشف التظليل المقلد بعد التركيب؟'",
        "aEn: 'Yes, if you notice small air bubbles, color turning purple, or feel the sun\\'s heat stinging your hand through the tinted glass, it\\'s poor dyed tint.'": "a: 'نعم، إذا لاحظت ظهور فقاعات هوائية صغيرة، أو تحول اللون للبنفسجي، أو إذا كنت تشعر بحرارة أشعة الشمس تلسع يدك عبر الزجاج المظلل، فهذا تظليل مصبوغ رديء.'",
        "qEn: 'Does fake tint damage the glass?'": "q: 'هل التظليل المقلد يضر الزجاج؟'",
        "aEn: 'The damage lies in the cheap glue that hardens due to the Saudi sun heat. When attempting to remove it later, the glue may rip and damage the thin defroster lines in the rear window.'": "a: 'الضرر يكمن في الغراء الرديء الذي يتيبس بسبب حرارة الشمس السعودية. عند محاولة إزالة الفيلم لاحقاً، قد يتمزق الغراء ويؤدي إلى تلف خطوط التسخين الرقيقة الموجودة في الزجاج الخلفي (Defroster lines).'",
        "qEn: 'A shop offered me nano-ceramic for 600 SAR with a 10-year warranty, makes sense?'": "q: 'محل عرض علي نانو سيراميك بـ 600 ريال وعليه ضمان 10 سنوات، هل يعقل؟'",
        "aEn: 'This is a classic trap. There is no original excellent US or Korean nano-ceramic at this price. The warranty is a \"personal shop warranty\" not a manufacturer warranty. If the shop closes, your right is lost.'": "a: 'هذا فخ كلاسيكي. لا يوجد نانو سيراميك أصلي أمريكي أو كوري ممتاز بهذا السعر. الضمان المقدم هو \"ضمان المحل الشخصي\" وليس ضمان الشركة المصنعة. إذا أغلق المحل، يضيع حقك.'"
    }
}

for file_path, replacements in files_data.items():
    try:
        with open(file_path, 'r', encoding='utf-8') as f:
            content = f.read()
            
        for eng_str, ar_str in replacements.items():
            if ar_str in content:
                content = content.replace(ar_str, f"{ar_str}, {eng_str}")
                
        with open(file_path, 'w', encoding='utf-8') as f:
            f.write(content)
            
        print(f"Updated {file_path}")
    except Exception as e:
        print(f"Error on {file_path}: {e}")
