import os

files_data = {
    'src/data/blog-content/building-insulation-electricity-savings.ts': {
        "textEn: 'Building Glass Insulation Service — Save up to 44% on Electricity Bill'": "text: 'خدمة عزل زجاج المباني — وفّر حتى 44% من فاتورة الكهرباء'",
        "textEn: 'Johnson Commercial Thermal Insulation Films'": "text: 'أفلام جونسون التجارية للعزل الحراري'",
        "quickAnswerEn: 'Insulating a 300m² villa\\'s windows with nano-ceramic film costs around 4,500 SAR and saves approximately 8,400 SAR annually on electricity. ROI period: only 6 months. The film achieves an SHGC below 0.25 as required by the Saudi Building Code SBC 601.'": "quickAnswer: 'عزل نوافذ فيلا 300م² بفيلم نانو سيراميك يُكلف حوالي 4,500 ريال ويُوفر ما يقارب 8,400 ريال سنوياً من فاتورة الكهرباء. مدة استرداد التكلفة: 6 أشهر فقط. الفيلم يحقق معيار SHGC أقل من 0.25 المطلوب في كود البناء السعودي SBC 601.'",
        "introEn: 'The electricity bill for an average villa in Jeddah ranges between 2,000 and 5,000 SAR monthly during peak summer. The main reason? Regular glass windows that allow 85% of infrared rays into the building, significantly increasing the AC load. Insulating windows with nano-ceramic films reduces this to just 22% — meaning real savings starting from the very first month. Here are actual calculations from our executed projects in Jeddah.'": "intro: 'فاتورة كهرباء فيلا متوسطة في جدة تتراوح بين 2,000 و 5,000 ريال شهرياً في ذروة الصيف. السبب الرئيسي؟ نوافذ الزجاج العادي التي تسمح بدخول 85% من الأشعة تحت الحمراء إلى المبنى، مما يرفع حمل التكييف بشكل كبير. عزل النوافذ بأفلام نانو سيراميك يخفض هذه النسبة إلى 22% فقط — وهذا يعني توفيراً حقيقياً يبدأ من أول شهر. هنا الحسابات الفعلية من مشاريعنا المنفذة في جدة.'",
        "headersEn: ['Film Type', 'Solar Energy Rejection (TSER)', 'SHGC Coefficient', 'Lifespan', 'Approx Cost (12 Windows)']": "headers: ['نوع الفيلم', 'حجب الطاقة الشمسية (TSER)', 'معامل SHGC', 'العمر الافتراضي', 'التكلفة التقريبية (12 نافذة)']",
        "rowsEn: [\n        ['Sputtered Multilayer (Reflective)', '78%', '0.15', '15 - 20 years', '6,000 - 8,000 SAR'],\n        ['Transparent Nano-Ceramic', '65%', '0.22', '10 - 15 years', '4,500 - 6,000 SAR'],\n        ['Economical Transparent Thermal Film', '55%', '0.30', '7 - 10 years', '2,500 - 4,000 SAR'],\n        ['Uninsulated Glass (Reference)', '15%', '0.82', '—', '0 SAR'],\n      ]": "rows: [\n        ['Sputtered Multilayer (عاكس)', '78%', '0.15', '15 - 20 سنة', '6,000 - 8,000 ر.س'],\n        ['نانو سيراميك شفاف', '65%', '0.22', '10 - 15 سنة', '4,500 - 6,000 ر.س'],\n        ['فيلم حراري شفاف اقتصادي', '55%', '0.30', '7 - 10 سنوات', '2,500 - 4,000 ر.س'],\n        ['زجاج بدون عزل (مرجع)', '15%', '0.82', '—', '0 ر.س'],\n      ]",
        "headingEn: 'How Heat Enters Through Windows — Physics Simply Explained'": "heading: 'كيف تدخل الحرارة عبر النوافذ — الفيزياء ببساطة'",
        "bodyEn: 'A single 1.5m wide window without insulation transmits equivalent to 500 watts of thermal energy per hour during peak summer. A villa with 12 windows = 6,000 watts of excess heat entering the building every hour. This number means the AC runs at maximum capacity all day to offset this massive heat load. Regular glass (Single-pane) passes 85% of infrared rays. Even double-glazed glass passes 60% without insulation film. Thermal film intercepts this path and rejects heat before it enters.'": "body: 'نافذة واحدة بعرض 1.5 متر بدون عزل تنقل ما يعادل 500 واط من الطاقة الحرارية كل ساعة في ذروة الصيف. فيلا بها 12 نافذة = 6,000 واط حرارة زائدة تدخل المبنى كل ساعة. هذا الرقم يعني أن المكيف يعمل بأقصى طاقته طوال اليوم لمعادلة هذا الحمل الحراري الهائل. الزجاج العادي (Single-pane) يمرر 85% من الأشعة تحت الحمراء. حتى الزجاج المزدوج (Double-glazed) يمرر 60% بدون فيلم عزل. الفيلم الحراري يقطع هذا المسار ويرفض الحرارة قبل أن تدخل.'",
        "headingEn: 'Field Case Study — A Villa in Al-Safa District, Jeddah'": "heading: 'دراسة حالة ميدانية — فيلا في حي الصفا بجدة'",
        "bodyEn: 'A 300m² villa with 12 windows facing west and south. Summer bill before insulation: 3,200 SAR monthly. Installed nano-ceramic film with 78% solar energy rejection. Result: Bill dropped to 1,800 SAR monthly — an immediate 44% savings. Monthly savings: 1,400 SAR × 6 summer months = 8,400 SAR annually. Over 10 years (film\\'s lifespan): 84,000 SAR net savings after deducting installation cost.'": "body: 'فيلا مساحتها 300م² بها 12 نافذة مطلة على الواجهة الغربية والجنوبية. فاتورة الصيف قبل العزل: 3,200 ريال شهرياً. تم تركيب فيلم نانو سيراميك بنسبة حجب 78% طاقة شمسية. النتيجة: الفاتورة انخفضت إلى 1,800 ريال شهرياً — توفير فوري بنسبة 44%. التوفير الشهري: 1,400 ريال × 6 أشهر صيف = 8,400 ريال سنوياً. على مدار 10 سنوات (عمر الفيلم الافتراضي): 84,000 ريال توفير صافٍ بعد خصم تكلفة التركيب.'",
        "headingEn: 'Economic Comparison: Film Insulation vs Full Glass Replacement'": "heading: 'مقارنة اقتصادية: العزل بالفيلم مقابل تغيير الزجاج بالكامل'",
        "bodyEn: 'Replacing 12 windows with Double-glazed glass: Costs 18,000 to 35,000 SAR, requires breaking frames and installation over 3 to 5 days, disrupting rooms during work. Insulating the same windows with nano-ceramic film: Costs only 4,500 SAR, installation within 3 to 4 hours, without any breaking or mess. Result: The film provides 80% of double-glazed performance at less than 15% of its price.'": "body: 'تغيير 12 نافذة لزجاج مزدوج (Double-glazed): تكلفة 18,000 إلى 35,000 ريال، يحتاج كسر الإطارات والتركيب خلال 3 إلى 5 أيام، مع تعطيل الغرف أثناء العمل. عزل نفس النوافذ بفيلم نانو سيراميك: تكلفة 4,500 ريال فقط، التركيب خلال 3 إلى 4 ساعات، بدون أي تكسير أو فوضى. النتيجة: الفيلم يوفر 80% من أداء الزجاج المزدوج بتكلفة لا تتجاوز 15% من سعره.'",
        "authorEn: 'Projects Team — AzelCore'": "author: 'فريق المشاريع — عزل كور'",
        "roleEn: 'Building & Facilities Insulation Dept.'": "role: 'قسم عزل المباني والمنشآت'",
        "textEn: 'The biggest mistake we see is property owners starting to change AC units before addressing the real cause. A 3-ton AC is useless if your windows are leaking 6,000 watts of heat every hour. Treat the source first by insulating the glass, then watch how AC consumption drops automatically.'": "text: 'أكبر خطأ نراه هو أن أصحاب العقارات يبدأون بتغيير المكيفات قبل معالجة السبب الحقيقي. لا فائدة من مكيف بقوة 3 طن إذا كانت نوافذك تسرب 6,000 واط حرارة كل ساعة. عالج المصدر أولاً بعزل الزجاج، ثم لاحظ كيف ينخفض استهلاك المكيف تلقائياً.'",
        "qEn: 'Does film glass insulation affect room lighting?'": "q: 'هل عزل الزجاج بالفيلم يؤثر على إضاءة الغرفة؟'",
        "aEn: 'No, modern films are designed to block heat (IR) while allowing 50% to 70% of natural light to pass. You won\\'t notice a major difference in lighting, but you will feel a huge difference in coolness.'": "a: 'لا، الأفلام الحديثة مصممة لحجب الحرارة (IR) مع السماح بمرور 50% إلى 70% من الضوء الطبيعي. لن تلاحظ فرقاً كبيراً في الإضاءة لكنك ستشعر بفرق ضخم في البرودة.'",
        "qEn: 'Does the film comply with the Saudi Building Code SBC 601?'": "q: 'هل الفيلم يتوافق مع كود البناء السعودي SBC 601؟'",
        "aEn: 'Yes. Nano-ceramic films achieve an SHGC between 0.15 and 0.22, which is below the maximum allowed (0.25) in Climate Zone 1 (Jeddah). We provide you with an official compliance certificate after installation.'": "a: 'نعم. أفلام النانو سيراميك تحقق معامل SHGC بين 0.15 و 0.22، وهو أقل من الحد الأقصى المسموح (0.25) في المنطقة المناخية 1 (جدة). نقدم لك شهادة مطابقة رسمية بعد التركيب.'",
        "qEn: 'How long does it take to install glass insulation for a full villa?'": "q: 'كم يستغرق تركيب عزل الزجاج لفيلا كاملة؟'",
        "aEn: 'An average villa (12-16 windows): 3 to 5 hours. Commercial building: 1 to 2 days. No need to evacuate the building or halt operations during installation.'": "a: 'فيلا متوسطة (12-16 نافذة): 3 إلى 5 ساعات. مبنى تجاري: يوم إلى يومين. لا يحتاج إخلاء المبنى أو تعطيل الأعمال أثناء التركيب.'",
        "warningEn: 'Installing film by an unspecialized technician causes air bubbles and poor adhesion — losing 30% of the film\\'s insulating performance. Choose an authorized center with an official warranty.'": "warning: 'تركيب الفيلم من فني غير متخصص يسبب فقاعات هوائية وعدم التصاق محكم — مما يُفقد الفيلم 30% من أدائه العازل. اختر مركزاً معتمداً بضمان رسمي.'",
        "ctaEn: 'Save thousands of Riyals on your electricity bill. Get a free thermal assessment for your building from AzelCore experts in Jeddah.'": "cta: 'وفّر آلاف الريالات من فاتورة الكهرباء. احصل على تقييم حراري مجاني لمبناك من خبراء عزل كور بجدة.'"
    },
    'src/data/blog-content/best-car-tint-jeddah-2026.ts': {
        "textEn: 'Book Your Original Thermal Tint in Jeddah Now'": "text: 'احجز تظليلك الحراري الأصلي بجدة الآن'",
        "textEn: 'Authorized Johnson Dealer — 10 Year Warranty'": "text: 'وكيل جونسون المعتمد — ضمان 10 سنوات'",
        "textEn: 'Authorized 3M Dealer in Jeddah'": "text: 'وكيل 3M المعتمد بجدة'",
        "quickAnswerEn: 'For the climate of Jeddah in 2026, Johnson Supreme IR and 3M Crystalline are considered the absolute best due to their TSER exceeding 60% and 99.9% UV rejection. Nano-ceramic relies on technologies that do not interfere with GPS signals while providing superior heat insulation without affecting night visibility.'": "quickAnswer: 'بالنسبة لمناخ جدة في عام 2026، يُعتبر جونسون Supreme IR و 3M Crystalline الأفضل بلا منازع لامتلاكهما نسبة TSER تتجاوز 60% وحجب UV بنسبة 99.9%. النانو سيراميك يعتمد على تقنيات لا تؤثر على إشارات الـ GPS مع توفير عزل حراري فائق دون التأثير على الرؤية الليلية.'",
        "introEn: 'Searching for the best car tint in Jeddah is no longer a luxury, but an absolute necessity given the extreme summer temperatures. With hundreds of shops offering \"nano-ceramic\" at varying prices, making the right choice requires technical understanding. In this guide, we review the top tested options for 2026 that combine performance, durability, and compliance with Saudi traffic laws.'": "intro: 'البحث عن أفضل تظليل سيارات في جدة لم يعد رفاهية، بل ضرورة قصوى مع درجات حرارة الصيف القاسية. مع وجود مئات المحلات التي تقدم \"النانو سيراميك\" بأسعار متفاوتة، يصبح الاختيار الصحيح يحتاج إلى فهم تقني. في هذا الدليل، نستعرض أفضل الخيارات المجربة لعام 2026 والتي تجمع بين الأداء، المتانة، والتوافق مع نظام المرور السعودي.'",
        "headersEn: ['Brand/Type', 'Nano-Ceramic Technology', 'Heat Rejection (IR)', 'Warranty', 'Best For']": "headers: ['العلامة التجارية/النوع', 'تقنية النانو سيراميك', 'عزل الحرارة (IR)', 'الضمان', 'أفضل استخدام']",
        "rowsEn: [\n        ['Johnson Supreme IR', 'Advanced Nano-Ceramic', 'Up to 97%', '10 Years', 'Families, High thermal load cars'],\n        ['3M Crystalline', 'Multi-layer (200 layers)', 'Up to 97%', 'Lifetime', 'Windshield, Highest transparency'],\n        ['Johnson Optik', 'Ceramic/Carbon blend', 'Up to 85%', '5 Years', 'Daily use, Budget friendly']\n      ]": "rows: [\n        ['Johnson Supreme IR', 'نانو سيراميك متقدم', 'يصل إلى 97%', '10 سنوات', 'العائلات، السيارات ذات الحمل الحراري العالي'],\n        ['3M Crystalline', 'متعدد الطبقات (200 طبقة)', 'يصل إلى 97%', 'مدى الحياة', 'الزجاج الأمامي، أعلى شفافية'],\n        ['Johnson Optik', 'مزيج سيراميك/كربون', 'يصل إلى 85%', '5 سنوات', 'الاستخدام اليومي، ميزانية متوسطة']\n      ]",
        "headingEn: 'Why Jeddah Requires Specific Specifications for Tinting?'": "heading: 'لماذا جدة تتطلب مواصفات خاصة للتظليل؟'",
        "bodyEn: 'High humidity combined with intense sunlight places double stress on the car\\'s AC. Using traditional dyed films is not only ineffective, but the adhesive deteriorates quickly due to the heat, causing bubbling and purple discoloration. Therefore, original Nano-Ceramic is the only standard that guarantees continuous protection and passenger comfort.'": "body: 'الرطوبة العالية مع أشعة الشمس العمودية تضع ضغطاً مضاعفاً على مكيف السيارة. استخدام الأفلام المصبوغة التقليدية ليس فقط غير فعال، بل إن الغراء يتلف بسرعة بسبب الحرارة مما يسبب فقاعات وتشوهات لونية (اللون البنفسجي). لذا، النانو سيراميك الأصلي هو المعيار الوحيد الذي يضمن الحماية المستمرة وراحة الركاب.'",
        "headingEn: 'Standards for Choosing the Best Tint in 2026'": "heading: 'معايير اختيار أفضل تظليل في 2026'",
        "bodyEn: 'Focus entirely on the TSER (Total Solar Energy Rejected) rate rather than just IR. A high TSER (above 55%) means the film physically repels total heat. Also, ensure the shop uses a computerized cutting system to avoid scratching the car glass with manual blades.'": "body: 'يجب التركيز بشكل كلي على نسبة TSER (إجمالي الطاقة الشمسية المرفوضة) وليس فقط الـ IR. نسبة TSER المرتفعة (فوق 55%) تعني أن الفيلم يطرد الحرارة الكلية فعلياً. كما يجب التأكد من أن المركز يستخدم نظام القص بالكمبيوتر لتجنب خدش زجاج السيارة بالمشارط اليدوية.'",
        "authorEn: 'Technical Team — AzelCore'": "author: 'الفريق الفني — عزل كور'",
        "roleEn: 'Car Accessories & Protection Dept.'": "role: 'قسم زينة وحماية السيارات'",
        "textEn: 'We have tested many brands over the years. We settled on Johnson and 3M because their actual performance matches the published data sheets. Don\\'t be fooled by 99% IR marketing without looking at the TSER percentage.'": "text: 'لقد اختبرنا العديد من العلامات التجارية عبر السنوات. استقرينا على جونسون و 3M لأن أداءهم الفعلي يطابق المواصفات الفنية المنشورة (Data sheets). لا تنخدع بتسويق 99% IR دون النظر إلى نسبة TSER.'",
        "qEn: 'What is the suitable tint shade for families in Jeddah?'": "q: 'ما هي درجة التظليل المناسبة للعائلات في جدة؟'",
        "aEn: 'Traffic laws allow 02 shade (around 30% transparency) for rear windows for families. It provides excellent privacy while maintaining high heat rejection capabilities.'": "a: 'يُسمح مرورياً بدرجة 02 (حوالي 30% شفافية) للنوافذ الخلفية للعائلات. توفر خصوصية ممتازة مع الحفاظ على قدرات عزل حراري عالية.'",
        "qEn: 'Does original tint need special maintenance?'": "q: 'هل التظليل الأصلي يحتاج إلى صيانة خاصة؟'",
        "aEn: 'It doesn\\'t need special maintenance, but it\\'s advised not to wash the windows from the inside with chemicals containing ammonia for at least two weeks after installation to ensure the adhesive cures completely.'": "a: 'لا يحتاج إلى صيانة خاصة، ولكن يُنصح بعدم غسيل الزجاج من الداخل بمواد كيميائية تحتوي على الأمونيا لمدة أسبوعين على الأقل بعد التركيب لضمان جفاف الغراء بالكامل.'",
        "warningEn: 'Non-authorized centers may issue fake warranties. The true warranty is electronic and registered in the official manufacturer\\'s system, allowing you to review it anywhere in the Kingdom.'": "warning: 'المراكز غير المعتمدة قد تصدر ضمانات ورقية وهمية. الضمان الحقيقي يكون إلكترونياً ومسجلاً في نظام الشركة الأم الرسمي، مما يتيح لك مراجعته في أي مكان بالمملكة.'",
        "ctaEn: 'Protect your car and family. View our offers for original Nano-Ceramic in Jeddah with an approved electronic warranty.'": "cta: 'احمي سيارتك وعائلتك. شاهد عروضنا على النانو سيراميك الأصلي في جدة مع الضمان الإلكتروني المعتمد.'"
    }
}

for file_path, replacements in files_data.items():
    try:
        with open(file_path, 'r', encoding='utf-8') as f:
            content = f.read()
            
        for eng_str, ar_str in replacements.items():
            if ar_str in content:
                content = content.replace(ar_str, f"{ar_str}, {eng_str}")
                
        with open(file_path, 'w', encoding='utf-8') as f:
            f.write(content)
            
        print(f"Updated {file_path}")
    except Exception as e:
        print(f"Error on {file_path}: {e}")
