import os

files_data = {
    'src/data/blog-content/car-tint-maintenance-guide.ts': {
        "textEn: 'Car Tinting with 10-Year Warranty + Free Annual Inspection'": "text: 'تظليل سيارات بضمان 10 سنوات + فحص سنوي مجاني'",
        "textEn: 'Authorized Johnson Dealer — Films with Lifetime Warranty'": "text: 'وكيل جونسون المعتمد — أفلام بضمان عمر السيارة'",
        "textEn: '3M Crystalline — Lifetime Warranty Against Peeling'": "text: '3M Crystalline — ضمان عمر السيارة ضد التقشر'",
        "quickAnswerEn: 'Proper tint maintenance extends its lifespan from 10 to 15+ years. Basic rules: wait 3-5 days before rolling down windows, exclusively use an ammonia-free cleaner, clean with a microfiber cloth only, do not stick anything on the tinted glass, and have the tint inspected annually at the center.'": "quickAnswer: 'العناية الصحيحة بالتظليل تمدد عمره من 10 إلى 15+ سنة. القواعد الأساسية: انتظر 3-5 أيام قبل تنزيل الزجاج، استخدم منظفاً خالياً من الأمونيا حصرياً، نظّف بقماش مايكروفايبر فقط، لا تلصق أي شيء على الزجاج المظلل، وافحص التظليل سنوياً لدى المركز.'",
        "introEn: 'You invested in an original nano-ceramic tint — now you need to maintain it properly. The mistake many car owners make is neglecting film care after installation, significantly reducing its lifespan. Proper care is very simple but makes a massive difference: a well-maintained film lasts 15+ years instead of 10. Here is a comprehensive guide from AzelCore experts.'": "intro: 'استثمرت في تظليل نانو سيراميك أصلي — الآن تحتاج أن تحافظ عليه بالشكل الصحيح. الخطأ الذي يرتكبه كثير من مالكي السيارات هو إهمال العناية بالفيلم بعد التركيب مما يقلل عمره الافتراضي بشكل ملحوظ. العناية السليمة بسيطة جداً لكنها تصنع فرقاً كبيراً: الفيلم الذي يُعتنى به يدوم 15+ سنة بدلاً من 10. هنا دليل شامل من خبراء عزل كور.'",
        "headersEn: ['Period After Installation', 'What To Do', 'What To Avoid']": "headers: ['الفترة بعد التركيب', 'ما يجب فعله', 'ما يجب تجنبه']",
        "rowsEn: [\n        ['First 48 Hours', 'Keep windows completely closed', 'Do NOT roll down windows at all — adhesive is wet'],\n        ['First 1-3 Weeks', 'Small bubbles are normal — they will disappear', 'Do not try to remove bubbles with a needle or card'],\n        ['First Month', 'Clean gently only when necessary', 'Do not stick anything on the tinted glass'],\n        ['After a Month (Always)', 'Ammonia-free cleaner + Microfiber', 'Avoid ammonia, rough sponges, and sharp tools'],\n        ['Annually', 'Free inspection at the center (VLT + edges)', 'Do not neglect inspection — early detection prevents damage']\n      ]": "rows: [\n        ['أول 48 ساعة', 'اترك الزجاج مغلقاً تماماً', 'لا تنزّل الزجاج إطلاقاً — اللاصق لم يجف'],\n        ['أول 1-3 أسابيع', 'الفقاعات الصغيرة طبيعية — ستختفي وحدها', 'لا تحاول إزالة الفقاعات بإبرة أو بطاقة'],\n        ['أول شهر', 'نظّف برفق عند الحاجة فقط', 'لا تلصق أي شيء على الزجاج المظلل'],\n        ['بعد شهر (دائماً)', 'منظف بدون أمونيا + مايكروفايبر', 'تجنب الأمونيا والإسفنج الخشن والأدوات الحادة'],\n        ['سنوياً', 'فحص مجاني في المركز (قياس VLT + أطراف)', 'لا تهمل الفحص — الاكتشاف المبكر يمنع التلف'],\n      ]",
        "headingEn: 'Why Ammonia is the Tint\\'s #1 Enemy'": "heading: 'لماذا الأمونيا عدوّ التظليل الأول'",
        "bodyEn: 'Traditional glass cleaners (like Windex) contain ammonia (NH3). Ammonia chemically reacts with the film\\'s adhesive layer, causing gradual corrosion that appears as purple or cloudy spots on the film. Exclusively use a cleaner labeled \"Ammonia-Free\" or a solution of water + mild liquid soap. Rule: Spray the cleaner onto the microfiber cloth first, then wipe the glass — do not spray directly onto the film.'": "body: 'منظفات الزجاج التقليدية (مثل Windex) تحتوي على الأمونيا (NH3). الأمونيا تتفاعل كيميائياً مع الطبقة اللاصقة للفيلم وتسبب تآكلاً تدريجياً يظهر على شكل بقع بنفسجية أو ضبابية في الفيلم. استخدم حصرياً منظفاً مكتوباً عليه \"Ammonia-Free\" أو محلول ماء + صابون سائل خفيف (جلي). القاعدة: رش المنظف على قماش المايكروفايبر أولاً ثم امسح الزجاج — لا ترش على الفيلم مباشرة.'",
        "headingEn: '5 Signs Your Tint Needs Replacement'": "heading: '5 علامات أن تظليلك يحتاج تبديل'",
        "bodyEn: 'First: Color turning purple or faded blue — meaning the dye has degraded and the film lost its heat rejection ability. Second: Large bubbles or blisters — a sign of adhesive failure. Third: Peeling from edges or corners. Fourth: Feeling the sun\\'s heat stinging your hand through the tinted glass — meaning thermal insulation has weakened. Fifth: Noticeable haziness obstructing interior visibility. If you notice any of these, the film\\'s life is over and requires full replacement.'": "body: 'أولاً: تحول اللون للبنفسجي أو الأزرق الباهت — هذا يعني أن الصبغة تحللت وفقد الفيلم قدرته على حجب الحرارة. ثانياً: ظهور فقاعات كبيرة أو انتفاخات — علامة على فشل اللاصق. ثالثاً: تقشّر من الأطراف أو الزوايا. رابعاً: شعورك بحرارة الشمس تلسع يدك عبر الزجاج المظلل — يعني أن العزل الحراري أصبح ضعيفاً. خامساً: ضبابية واضحة تعيق الرؤية من الداخل. إذا لاحظت أياً من هذه العلامات، فعمر الفيلم انتهى ويحتاج استبدالاً كاملاً.'",
        "headingEn: 'The Fatal Mistake: Applying New Film Over the Old One'": "heading: 'الخطأ الكارثي: لصق فيلم جديد فوق القديم'",
        "bodyEn: 'Some cheap shops offer to install new film directly over the damaged old film. This is a fatal mistake! The result: trapped air bubbles between layers, distorted vision (especially at night), and weak adhesion causing rapid peeling. The only correct solution: fully remove the old film (including adhesive residue), clean and prep the glass, then install the new film. Professional removal costs 150-300 SAR — but guarantees perfect results for the new film.'": "body: 'بعض المحلات الرخيصة تعرض عليك تركيب فيلم جديد مباشرة فوق الفيلم القديم التالف. هذا خطأ فادح! النتيجة: فقاعات هوائية محبوسة بين الطبقتين، رؤية مشوشة خاصة ليلاً، التصاق ضعيف يسبب تقشراً سريعاً. الحل الصحيح الوحيد: إزالة الفيلم القديم بالكامل (يشمل إزالة بقايا الغراء)، تنظيف الزجاج وتجهيزه، ثم تركيب الفيلم الجديد. الإزالة الاحترافية تكلف 150-300 ريال — لكنها تضمن نتيجة مثالية للفيلم الجديد.'",
        "authorEn: 'Eng. Ahmed Salem'": "author: 'م. أحمد سالم'",
        "roleEn: 'Thermal Insulation Consultant — AzelCore'": "role: 'مستشار العزل الحراري — عزل كور'",
        "textEn: 'The most common cause of premature tint failure is using ammonia-based cleaners. A client invests 2,500 SAR in premium tint, then destroys it with a 15 SAR cleaner. Use only water and soap — the simplest and safest solution. I highly recommend an annual tint inspection at our center — we offer this service for free to all our clients.'": "text: 'أكثر سبب لتلف التظليل المبكر هو استخدام منظفات تحتوي أمونيا. العميل يستثمر 2,500 ريال في تظليل ممتاز ثم يدمره بمنظف يكلف 15 ريالاً. استخدم ماء وصابون فقط — أبسط حل وأكثرها أماناً. وأنصح بفحص التظليل سنوياً في المركز — نحن نقدم هذه الخدمة مجاناً لجميع عملائنا.'",
        "qEn: 'How long does tint take to cure completely in Jeddah?'": "q: 'كم يحتاج التظليل ليجف تماماً في جدة؟'",
        "aEn: 'In summer (high humidity): 5-7 days. In winter (lower humidity): 3-4 days. During the curing period, never roll down the windows — even if the film looks dry from the outside, the adhesive needs more time.'": "a: 'في الصيف (رطوبة عالية): 5-7 أيام. في الشتاء (رطوبة أقل): 3-4 أيام. خلال فترة الجفاف، لا تنزّل الزجاج أبداً — حتى لو بدا الفيلم جافاً من الخارج، فاللاصق يحتاج وقتاً أطول.'",
        "qEn: 'Does cleaning the car in a pressure wash affect the tint?'": "q: 'هل تنظيف السيارة في مغسلة ضغط يؤثر على التظليل؟'",
        "aEn: 'Water pressure on the outside glass has no effect. The issue arises when cleaning the inside glass (tinted side) with rough tools or high pressure. Ask the car wash to use only microfiber on the interior side.'": "a: 'ضغط الماء على الزجاج من الخارج لا يؤثر. المشكلة تكون عند تنظيف الزجاج من الداخل (الجهة المظللة) بأدوات خشنة أو ضغط عالٍ. اطلب من المغسلة استخدام مايكروفايبر فقط على الجهة الداخلية.'",
        "qEn: 'I accidentally put a sticker on the tinted glass — what should I do?'": "q: 'لصقت ملصقاً على الزجاج المظلل بالخطأ — ماذا أفعل؟'",
        "aEn: 'Do not try to forcefully peel it or use a blade. Soak the sticker with soapy water, leave it for 10 minutes, then peel it extremely slowly. If adhesive residue remains, gently use rubbing alcohol (Isopropyl Alcohol) — never use acetone.'": "a: 'لا تحاول نزع الملصق بقوة أو باستخدام شفرة. بلّل الملصق بمحلول ماء وصابون واتركه 10 دقائق ثم ازله ببطء شديد. إذا بقيت آثار غراء، استخدم كحولاً طبياً (Isopropyl Alcohol) برفق — لا تستخدم أسيتون أبداً.'",
        "warningEn: 'Cheap tint (under 600 SAR for a full sedan) needs replacement after one year — meaning you pay twice. Original nano-ceramic lasts 10-15 years with simple care.'": "warning: 'التظليل الرخيص (أقل من 600 ريال لسيدان كاملة) يحتاج تبديلاً بعد سنة واحدة — يعني أنك تدفع مرتين. النانو سيراميك الأصلي يدوم 10-15 سنة بعناية بسيطة.'",
        "ctaEn: 'Need an inspection for your current tint or a professional replacement? Contact AzelCore — annual inspections are free for our clients.'": "cta: 'تحتاج فحصاً لتظليلك الحالي أو استبدالاً احترافياً؟ تواصل مع عزل كور — الفحص السنوي مجاني لعملائنا.'"
    },
    'src/data/blog-content/how-to-spot-fake-tint.ts': {
        "textEn: 'Book Guaranteed Nano-Ceramic Tint in Jeddah'": "text: 'احجز تظليل نانو سيراميك مضمون بجدة'",
        "textEn: 'Authorized Johnson Dealer — 100% Original Tint'": "text: 'وكيل جونسون المعتمد — تظليل أصلي 100%'",
        "textEn: 'Authorized 3M Dealer — Ensure Quality with Warranty'": "text: 'وكيل 3M المعتمد — تأكد من الجودة مع الضمان'",
        "quickAnswerEn: 'You can spot fake tint through 4 signs: suspiciously low price (less than 800 SAR for a full car), lack of a physical IR meter test before installation, warranty not being electronic/registered in the parent company\\'s system, and absence of an engraved watermark on the film (like 3M or Johnson).'": "quickAnswer: 'يمكنك اكتشاف التظليل المقلد عبر 4 علامات: السعر المنخفض بشكل مريب (أقل من 800 ريال لسيارة كاملة)، عدم وجود فحص حقيقي بجهاز IR Meter قبل التركيب، عدم كون الضمان إلكترونياً ومسجلاً في نظام الشركة الأم، وغياب الشعار المائي المحفور على الفيلم (مثل 3M أو جونسون).'",
        "introEn: 'The tinting market in Saudi Arabia is full of counterfeit products claiming to be \"Nano-Ceramic.\" Unfortunately, many car owners fall victim to these scams, paying hundreds of Riyals for films that provide zero thermal insulation and fade within months. In this guide, we reveal the tricks used by unauthorized shops and how to ensure you are getting an original product.'": "intro: 'سوق التظليل في السعودية مليء بالمنتجات المقلدة التي تدعي أنها \"نانو سيراميك\". للأسف، يقع الكثير من أصحاب السيارات ضحية لهذه الخدع، ويدفعون مئات الريالات في أفلام لا تقدم أي عزل حراري وتبهت خلال أشهر. في هذا الدليل، نكشف لك الحيل التي تستخدمها المحلات غير المعتمدة وكيف تتأكد من حصولك على منتج أصلي.'",
        "headersEn: ['Feature', 'Original Nano-Ceramic', 'Counterfeit/Commercial Tint']": "headers: ['الميزة', 'النانو سيراميك الأصلي', 'التظليل المقلد/التجاري']",
        "rowsEn: [\n        ['IR Rejection', 'Tested in front of you (up to 97%)', 'No test, just claims'],\n        ['Color Stability', 'Does not fade or turn purple', 'Turns purple within 3-6 months'],\n        ['Warranty', 'Electronic, verifiable online', 'Paper only, shop may refuse claims'],\n        ['Clarity', 'High clarity, no distortion', 'Blurry, especially at night'],\n        ['Price', 'Logical based on materials', 'Suspiciously cheap (e.g., 300 SAR full car)']\n      ]": "rows: [\n        ['عزل الحرارة (IR)', 'يُفحص أمامك (يصل لـ 97%)', 'لا يوجد فحص، مجرد ادعاءات'],\n        ['ثبات اللون', 'لا يبهت ولا يتحول للبنفسجي', 'يتحول للبنفسجي خلال 3-6 أشهر'],\n        ['الضمان', 'إلكتروني، يمكن التحقق منه أونلاين', 'ورقي فقط، المحل قد يرفض التعويض'],\n        ['الوضوح', 'وضوح عالي، لا تشوه في الرؤية', 'ضبابي، خاصة في الليل'],\n        ['السعر', 'منطقي بناءً على تكلفة المواد', 'رخيص بشكل مريب (مثلاً 300 ريال لسيارة)']\n      ]",
        "headingEn: 'The Fake IR Test Trick'": "heading: 'حيلة فحص الحرارة الوهمي'",
        "bodyEn: 'Some shops use a modified heat lamp or a fake IR meter that always reads high insulation. The solution? Ask them to test the film using a standard IR meter against a piece of regular glass, then against the tinted glass. Ensure the meter is a known brand and the test is done right in front of you.'": "body: 'بعض المحلات تستخدم لمبة حرارة معدلة أو جهاز فحص (IR Meter) مزيف يقرأ دائماً نسبة عزل عالية. الحل؟ اطلب فحص الفيلم بجهاز قياس قياسي أمام عينيك بمقارنة قطعة زجاج عادية بقطعة مظللة. تأكد أن الجهاز من علامة تجارية معروفة وأن الفحص يتم فعلياً أمامك.'",
        "headingEn: 'The Paper Warranty Illusion'": "heading: 'وهم الضمان الورقي'",
        "bodyEn: 'A shop gives you a paper invoice saying \"10 Year Warranty.\" After a year, the tint peels off. You return, and they tell you \"The warranty doesn\\'t cover this\" or the shop has changed names. Original brands (like Johnson or 3M) register your warranty electronically using your vehicle\\'s VIN, valid across their entire authorized network.'": "body: 'المحل يعطيك فاتورة ورقية مكتوب عليها \"ضمان 10 سنوات\". بعد سنة، يتقشر التظليل. تعود إليهم، فيقولون لك \"الضمان لا يشمل هذا\" أو تجد أن المحل قد غيّر اسمه. العلامات التجارية الأصلية (مثل جونسون أو 3M) تسجل ضمانك إلكترونياً برقم هيكل السيارة (VIN)، ويكون صالحاً في جميع فروع وكلائهم المعتمدين.'",
        "authorEn: 'Quality Control Team — AzelCore'": "author: 'فريق ضبط الجودة — عزل كور'",
        "roleEn: 'Quality & Testing Dept.'": "role: 'قسم الجودة والاختبار'",
        "textEn: 'We frequently remove fake tint from customers\\' cars. The most dangerous part isn\\'t the financial loss, but the poor adhesive that gets baked onto the glass, sometimes damaging the rear defroster lines during removal. Always verify the authorized dealer certificate.'": "text: 'نقوم باستمرار بإزالة تظليل مقلد من سيارات العملاء. الخطر الأكبر ليس الخسارة المالية، بل الغراء الرديء الذي يلتصق بالزجاج ويصعب إزالته، وأحياناً يتلف خطوط التسخين الخلفية. تأكد دائماً من شهادة الوكالة المعتمدة.'",
        "qEn: 'Are all Nano-Ceramic films the same?'": "q: 'هل كل أفلام النانو سيراميك متماثلة؟'",
        "aEn: 'No. \"Nano-Ceramic\" is just a technology name, like \"LED TV.\" There are high-quality American ceramics and cheap commercial ceramics. Look for established brands with verifiable TSER ratings.'": "a: 'لا. \"نانو سيراميك\" هو مجرد اسم تقنية، مثل \"تلفزيون LED\". هناك سيراميك أمريكي عالي الجودة وهناك سيراميك تجاري رخيص. ابحث عن العلامات التجارية العريقة ذات نسب TSER الموثقة.'",
        "qEn: 'Can I verify a 3M dealer online?'": "q: 'هل يمكنني التحقق من وكيل 3M أونلاين؟'",
        "aEn: 'Yes, 3M provides a dealer locator on their official website. Always check if the shop you are visiting is listed there before proceeding.'": "a: 'نعم، 3M توفر أداة للبحث عن الوكلاء المعتمدين على موقعهم الرسمي. تأكد دائماً أن المحل الذي تتعامل معه مدرج في الموقع قبل التركيب.'",
        "warningEn: 'If you install fake tint and it fails periodic inspection, you bear the cost of the traffic fine, the expensive removal cost, and the cost of new tint.'": "warning: 'في حال تركيب تظليل مقلد وفشله في اجتياز الفحص الدوري، ستتحمل تكلفة غرامة المرور، تكلفة إزالة التظليل الباهظة، وتكلفة تركيب تظليل جديد.'",
        "ctaEn: 'At AzelCore, we test every film with an IR meter in front of your eyes before installation. Contact us to protect your car with a verified electronic warranty.'": "cta: 'في عزل كور، نختبر كل فيلم بجهاز الـ IR Meter أمام عينيك قبل التركيب. تواصل معنا لحماية سيارتك بضمان إلكتروني معتمد.'"
    },
    'src/data/blog-content/jeddah-heat-car-damage.ts': {
        "textEn: 'Protect Your Car from Jeddah Heat — Nano-Ceramic Tint'": "text: 'احمِ سيارتك من حرارة جدة — تظليل نانو سيراميك'",
        "textEn: 'Johnson Supreme IR — 97% Heat Rejection'": "text: 'جونسون Supreme IR — 97% حجب حرارة'",
        "textEn: '3M Crystalline — The Perfect Windshield Solution'": "text: '3M Crystalline — الحل الأمثل للزجاج الأمامي'",
        "quickAnswerEn: 'Jeddah\\'s heat (48°C+ with 80% humidity) causes 7 direct damages to your car: cracking leather seats, fading dashboard, damaging electronic screens, increasing fuel consumption by 15-20%, deteriorating rubber, harming eyes and skin, and fading interior trim. These damages cost between 8,300 and 17,800 SAR annually — whereas a full nano-ceramic tint costs 1,500-3,200 SAR one time.'": "quickAnswer: 'حرارة جدة (48°C+ مع رطوبة 80%) تسبب 7 أضرار مباشرة لسيارتك: تشقق الفرش الجلدي، بهتان الطبلون، تلف الشاشات الإلكترونية، زيادة استهلاك الوقود 15-20%، تآكل المطاط، ضرر العيون والبشرة، وبهتان الطلاء الداخلي. تكلفة هذه الأضرار تتراوح بين 8,300 و 17,800 ريال سنوياً — بينما تظليل نانو سيراميك كامل يُكلف 1,500-3,200 ريال مرة واحدة.'",
        "introEn: 'Jeddah\\'s sun is unforgiving — temperatures exceeding 48°C in peak summer with coastal humidity over 80%, creating an extremely harsh environment for your car inside and out. Damage accumulates silently daily and only becomes apparent when it\\'s too late. In this guide, we quantify the true damage with numbers and actual costs — explaining why tinting is not a luxury, but an investment protecting your car\\'s value.'": "intro: 'شمس جدة لا ترحم — درجات حرارة تتجاوز 48°C في ذروة الصيف مع رطوبة بحرية تفوق 80%، مما يخلق بيئة قاسية جداً على سيارتك من الداخل والخارج. الأضرار تتراكم يومياً بشكل صامت ولا تظهر للعيان إلا بعد فوات الأوان. في هذا الدليل، نحصي لك الأضرار الحقيقية بالأرقام والتكاليف الفعلية — ونوضح لماذا التظليل ليس رفاهية بل استثمار يحمي قيمة سيارتك.'",
        "headersEn: ['Type of Damage', 'Approximate Repair Cost', 'Time to Appear Without Tint']": "headers: ['نوع الضرر', 'التكلفة التقريبية للإصلاح', 'مدة ظهور الضرر بدون تظليل']",
        "rowsEn: [\n        ['Cracking Leather Seats', '1,500 - 3,000 SAR', '4 - 6 months'],\n        ['Dashboard Replacement/Repair', '800 - 2,000 SAR', '6 - 12 months'],\n        ['Replacement Infotainment Screen', '3,000 - 8,000 SAR', '12 - 18 months'],\n        ['Excess Fuel Consumption (Annual)', '2,400 - 3,600 SAR', 'Immediate'],\n        ['Door Seal Replacement', '600 - 1,200 SAR', '2 - 3 years'],\n        ['<strong>Total Potential Annual Cost</strong>', '<strong>8,300 - 17,800 SAR</strong>', '—'],\n        ['Tinting Cost (One-time)', '1,500 - 3,200 SAR', '<strong>Lasts 10-15 years</strong>'],\n      ]": "rows: [\n        ['تشقق الفرش الجلدي', '1,500 - 3,000 ر.س', '4 - 6 أشهر'],\n        ['تبديل/إصلاح الطبلون', '800 - 2,000 ر.س', '6 - 12 شهراً'],\n        ['شاشة معلوماتية بديلة', '3,000 - 8,000 ر.س', '12 - 18 شهراً'],\n        ['استهلاك وقود زائد (سنوي)', '2,400 - 3,600 ر.س', 'فوري'],\n        ['تبديل جوانات الأبواب', '600 - 1,200 ر.س', '2 - 3 سنوات'],\n        ['<strong>الإجمالي المحتمل سنوياً</strong>', '<strong>8,300 - 17,800 ر.س</strong>', '—'],\n        ['تكلفة التظليل (مرة واحدة)', '1,500 - 3,200 ر.س', '<strong>يدوم 10-15 سنة</strong>'],\n      ]",
        "headingEn: 'Cabin Temperature: The Shocking Number'": "heading: 'درجة حرارة المقصورة: الرقم الصادم'",
        "bodyEn: 'An untinted car parked in Jeddah\\'s sun for just one hour: cabin temperature reaches 72-81°C (measured with FLIR thermal camera). The steering wheel hits 65°C (enough to burn skin). The dashboard exceeds 90°C in sun-exposed areas. After installing nano-ceramic: the cabin stays under 42°C in the same conditions — a 30-39 degree Celsius difference! The AC cools the car in 4-5 minutes instead of 12-15 minutes.'": "body: 'سيارة بدون تظليل متوقفة في شمس جدة لمدة ساعة واحدة فقط: درجة حرارة المقصورة تصل إلى 72-81°C (مقاسة بكاميرا حرارية FLIR). المقود يصل إلى 65°C (كافٍ لحرق الجلد). الطبلون يتجاوز 90°C في المنطقة المكشوفة للشمس. بعد تركيب نانو سيراميك: المقصورة لا تتجاوز 42°C في نفس الظروف — فرق 30-39 درجة مئوية! المكيف يبرّد السيارة خلال 4-5 دقائق بدلاً من 12-15 دقيقة.'",
        "headingEn: 'Hidden Damages: Leather, Electronics, and Rubber'": "heading: 'الأضرار الخفية: الجلد والإلكترونيات والمطاط'",
        "bodyEn: 'UV rays break down chemical bonds in natural and synthetic leather — seats lose 23% of elasticity in 6 months without protection. Modern interactive screens (LCD/OLED) are highly sensitive to temperatures over 60°C — developing permanent black spots (Dead Pixels) and sluggish response. Rubber door seals dry and crack from repeated thermal expansion/contraction cycles — resulting in rainwater leaks and annoying wind noise while driving.'": "body: 'الأشعة فوق البنفسجية (UV) تكسر الروابط الكيميائية في الجلد الطبيعي والصناعي — الفرش يفقد 23% من مرونته خلال 6 أشهر بدون حماية. الشاشات التفاعلية الحديثة (LCD/OLED) حساسة جداً لدرجات الحرارة فوق 60°C — تظهر بقع سوداء دائمة (Dead Pixels) وتباطؤ في الاستجابة. جوانات الأبواب المطاطية تجف وتتشقق بسبب دورات التمدد والانكماش الحراري المتكررة — النتيجة: تسريب مياه الأمطار وصوت هواء مزعج أثناء القيادة.'",
        "headingEn: 'Your Car Prep Checklist for Jeddah Summer 2026'": "heading: 'قائمة تجهيز سيارتك لصيف جدة 2026'",
        "bodyEn: 'Full nano-ceramic tint for all glass (Priority #1). Clear insulation for the windshield (3M Crystalline CR70 or Johnson Supreme IR shade 00). Windshield sunshade when parked. PPF for hood and roof if it\\'s a luxury car. Steering wheel cover when parked to protect from direct heat. AC check and freon refill before June. Exterior paint polishing to protect the clear coat from rays.'": "body: 'تظليل نانو سيراميك كامل لجميع الزجاج (الأولوية رقم 1). عازل شفاف للزجاج الأمامي (3M Crystalline CR70 أو Johnson Supreme IR درجة 00). حاجب شمسي للزجاج الأمامي عند الوقوف. PPF للكابوت والسقف إذا كانت السيارة فارهة. تغطية المقود عند الوقوف لحمايته من الحرارة المباشرة. فحص المكيف وتعبئة الفريون قبل يونيو. إعادة تلميع الطلاء الخارجي لحماية الكلير كوت من الأشعة.'",
        "authorEn: 'Eng. Ahmed Salem'": "author: 'م. أحمد سالم'",
        "roleEn: 'Thermal Insulation Consultant — AzelCore'": "role: 'مستشار العزل الحراري — عزل كور'",
        "textEn: 'Every day you delay tinting = additional irreversible damage. Cracked leather isn\\'t repaired — it\\'s replaced. A damaged screen isn\\'t restored — it\\'s swapped. Tinting is the cheapest possible insurance for your car in Jeddah\\'s climate. I advise every car owner to tint before the end of May to avoid peak summer.'": "text: 'كل يوم تأخير في تركيب التظليل = ضرر إضافي لا يمكن عكسه. الجلد المتشقق لا يُصلح — يُستبدل. الشاشة التالفة لا تُرمّم — تُبدّل. التظليل هو أرخص تأمين ممكن لسيارتك في مناخ جدة. أنصح كل مالك سيارة بالتظليل قبل نهاية مايو لتجنب ذروة الصيف.'",
        "qEn: 'Is tinting alone enough to protect my car from Jeddah heat?'": "q: 'هل التظليل وحده كافٍ لحماية سيارتي من حرارة جدة؟'",
        "aEn: 'Tinting protects against 97% of IR and 99% of UV rays — it\\'s the primary defense line. But for full protection, add a sunshade when parked and park in the shade whenever possible. PPF protects the exterior paint as an extra layer.'": "a: 'التظليل يحمي من 97% من الأشعة تحت الحمراء و99% من الأشعة فوق البنفسجية — وهو أهم خط دفاع. لكن للحماية الكاملة، أضف حاجب شمسي عند الوقوف واركن في الظل كلما أمكن. PPF يحمي الطلاء الخارجي كطبقة إضافية.'",
        "qEn: 'How much does cabin temperature drop after tinting?'": "q: 'كم درجة حرارة تنخفض المقصورة بعد التظليل؟'",
        "aEn: 'Based on our field measurements in August in Jeddah: Untinted cabin reaches 81°C. With nano-ceramic (Johnson Supreme IR): Stays under 42°C. Difference: 39 degrees Celsius — a difference instantly felt by anyone sitting in the car.'": "a: 'بناءً على قياساتنا الميدانية في أغسطس بجدة: المقصورة بدون تظليل تصل إلى 81°C. مع نانو سيراميك (Johnson Supreme IR): لا تتجاوز 42°C. الفرق: 39 درجة مئوية — وهو فرق يحسه كل من يجلس في السيارة فوراً.'",
        "qEn: 'My car is new — should I tint immediately or wait?'": "q: 'سيارتي جديدة — هل أحتاج تظليل فوراً أم أنتظر؟'",
        "aEn: 'The sooner you tint, the more you protect your car. Damage starts from day one — even if you don\\'t notice it. We recommend tinting within the first two weeks of purchase, especially if you are in Jeddah.'": "a: 'كلما ظللت أبكر كلما حميت سيارتك أكثر. الأضرار تبدأ من اليوم الأول — حتى لو لم تلاحظها. ننصح بالتظليل خلال أول أسبوعين من شراء السيارة، خاصة إذا كنت في جدة.'",
        "warningEn: 'All mentioned damages are cumulative — starting from day one under the sun but you only notice them months later. Immediate tinting before summer is the smartest and most economical solution. Every delayed day = irreversible damage.'": "warning: 'جميع الأضرار المذكورة تراكمية — تبدأ من أول يوم تحت الشمس لكنك لا تلاحظها إلا بعد أشهر. التظليل الفوري قبل الصيف هو الحل الأذكى والأوفر. كل يوم تأخير = ضرر لا يُعكس.'",
        "ctaEn: 'Don\\'t wait until your car is damaged. Book a comprehensive tint now before Jeddah\\'s peak summer.'": "cta: 'لا تنتظر حتى تتلف سيارتك. احجز تظليلاً شاملاً الآن قبل ذروة صيف جدة.'"
    }
}

for file_path, replacements in files_data.items():
    try:
        with open(file_path, 'r', encoding='utf-8') as f:
            content = f.read()
            
        for eng_str, ar_str in replacements.items():
            if ar_str in content:
                content = content.replace(ar_str, f"{ar_str}, {eng_str}")
                
        with open(file_path, 'w', encoding='utf-8') as f:
            f.write(content)
            
        print(f"Updated {file_path}")
    except Exception as e:
        print(f"Error on {file_path}: {e}")
