import os

files_data = {
    'src/data/blog-content/ppf-vs-ceramic-coating.ts': {
        "textEn: 'Comprehensive Car Protection Service — Tint + PPF in Jeddah'": "text: 'خدمة حماية السيارات الشاملة — تظليل + PPF بجدة'",
        "textEn: 'Johnson Thermal & Paint Protection Films'": "text: 'أفلام جونسون للحماية الحرارية وحماية الطلاء'",
        "quickAnswerEn: 'PPF (Paint Protection Film) protects against scratches and gravel — it\\'s 150-200 microns thick and self-healing. Ceramic Coating gives gloss and water/dirt repellency — only 2-5 microns thick. They are completely different products: PPF = physical protection, Ceramic = chemical protection. The ideal solution: combine both.'": "quickAnswer: 'PPF (فيلم حماية الطلاء) يحمي من الخدوش والحصى — سمكه 150-200 ميكرون ويلتئم ذاتياً. Ceramic Coating (طلاء السيراميك) يعطي لمعاناً وحماية من الماء والأوساخ — سمكه 2-5 ميكرون فقط. الاثنان منتجان مختلفان تماماً: PPF = حماية فيزيائية، Ceramic = حماية كيميائية. الحل الأمثل: الجمع بينهما.'",
        "introEn: 'A recurring question among luxury car owners: \"Should I install PPF or ceramic coating?\" The short answer: they are two products that protect two different things. PPF is a physical shield against scratches and gravel, while Ceramic Coating is a chemical layer against water, dirt, and oxidation. In Jeddah\\'s climate specifically (80%+ humidity and sea salt spray), understanding the difference is a decision that protects your investment in your car.'": "intro: 'السؤال الذي يتكرر كثيراً بين أصحاب السيارات الفارهة: \"أركب PPF ولا طلاء سيراميك؟\" الإجابة المختصرة: هما منتجان يحميان شيئين مختلفين. PPF هو درع فيزيائي ضد الخدوش والحصى، بينما Ceramic Coating هو طبقة كيميائية ضد الماء والأوساخ والأكسدة. في مناخ جدة تحديداً (رطوبة 80%+ ورذاذ ملحي بحري)، فهم الفرق بينهما قرار يحمي استثمارك في سيارتك.'",
        "headersEn: ['Comparison Point', 'PPF (Paint Protection Film)', 'Ceramic Coating']": "headers: ['وجه المقارنة', 'PPF (فيلم حماية الطلاء)', 'Ceramic Coating (طلاء سيراميك)']",
        "rowsEn: [\n        ['Thickness', '150 - 200 microns (Thick)', '2 - 5 microns (Very thin)'],\n        ['Scratch Protection', 'Excellent — Absorbs scratches & self-heals', 'Poor — Does not prevent deep scratches'],\n        ['Gravel & Sand Protection', 'Excellent — Full physical barrier', 'Does not protect from gravel'],\n        ['Gloss & Appearance', 'Good (Light gloss)', '<strong>Excellent</strong> — Deep glass gloss'],\n        ['Water Resistance (Hydrophobic)', 'Good', '<strong>Excellent</strong> — Water slides right off'],\n        ['Lifespan', '7 - 10 years', '2 - 5 years (needs renewal)'],\n        ['Cost (Hood + Fenders)', '2,500 - 4,000 SAR', 'Full car: 1,500 - 3,000 SAR'],\n        ['Actual Annual Cost', '~375 SAR/year', '~750 SAR/year']\n      ]": "rows: [\n        ['السمك', '150 - 200 ميكرون (سميك)', '2 - 5 ميكرون (رقيق جداً)'],\n        ['حماية من الخدوش', 'ممتازة — يمتص الخدش ويلتئم ذاتياً', 'ضعيفة — لا يمنع الخدوش العميقة'],\n        ['حماية من الحصى والرمل', 'ممتازة — حاجز فيزيائي كامل', 'لا يحمي من الحصى'],\n        ['اللمعان والمظهر', 'جيد (لمعان خفيف)', '<strong>ممتاز</strong> — لمعان عميق زجاجي'],\n        ['مقاومة الماء (Hydrophobic)', 'جيدة', '<strong>ممتازة</strong> — الماء ينزلق فوراً'],\n        ['العمر الافتراضي', '7 - 10 سنوات', '2 - 5 سنوات (يحتاج تجديد)'],\n        ['التكلفة (كابوت + رفارف)', '2,500 - 4,000 ر.س', 'كامل السيارة: 1,500 - 3,000 ر.س'],\n        ['التكلفة السنوية الفعلية', '~375 ر.س/سنة', '~750 ر.س/سنة'],\n      ]",
        "headingEn: 'PPF: The Invisible Shield for Your Car\\'s Paint'": "heading: 'PPF: الدرع غير المرئي لطلاء سيارتك'",
        "bodyEn: 'PPF is a transparent polyurethane film, 150-200 microns thick, applied to the car\\'s exterior paint. Its most important feature is Self-Healing: light scratches automatically disappear when exposed to sun heat or hot water. It protects against flying gravel on highways, acidic bug splatters, and UV rays that cause paint fading. Its thickness is 8-10 times that of ceramic coating.'": "body: 'PPF هو فيلم بولي يوريثان شفاف بسمك 150-200 ميكرون يُركب على الطلاء الخارجي للسيارة. أهم ميزة فيه هي خاصية الالتئام الذاتي (Self-Healing): الخدوش الخفيفة تختفي تلقائياً عند تعرضها لحرارة الشمس أو الماء الساخن. يحمي من الحصى الطائر على الطرق السريعة، آثار الحشرات الحمضية، وأشعة UV التي تسبب بهتان الطلاء. سمكه يعادل 8-10 أضعاف سمك طلاء السيراميك.'",
        "headingEn: 'Ceramic Coating: The Shield of Gloss and Cleanliness'": "heading: 'Ceramic Coating: درع اللمعان والنظافة'",
        "bodyEn: 'Ceramic Coating is a liquid layer (SiO2), 2-5 microns thick, applied to the paint where it chemically hardens. It gives the car a deep glass-like gloss and hydrophobic properties — raindrops and water slide off immediately, carrying dirt away. However, it does not protect against strong scratches or gravel. Its lifespan is 2-5 years depending on quality and requires periodic renewal.'": "body: 'Ceramic Coating هو طبقة سائلة (SiO2) بسمك 2-5 ميكرون تُوضع على الطلاء وتتصلب كيميائياً. تمنح السيارة لمعاناً عميقاً يشبه الزجاج وخاصية طاردة للماء (Hydrophobic) — قطرات المطر والماء تنزلق فوراً حاملة معها الأوساخ. لكنها لا تحمي من الخدوش القوية أو الحصى. عمرها 2-5 سنوات حسب الجودة وتحتاج تجديداً دورياً.'",
        "headingEn: 'The Perfect Combination for Jeddah\\'s Climate'": "heading: 'التركيبة المثالية لمناخ جدة'",
        "bodyEn: 'Jeddah\\'s high humidity (80%+) and coastal salt spray noticeably accelerate paint corrosion — especially in neighborhoods like Ash Shati, Al Khalidiyyah, and Az Zahra. Salt causes micro-pitting in the paint within 12-18 months without protection. The ideal solution is combining them: PPF on exposed areas (hood, front fenders, side mirrors) + Ceramic Coating on the rest of the car. Total cost: 4,000-8,000 SAR — but it\\'s much cheaper than repairing a single scratch on a luxury car\\'s paint (800-2,000 SAR per scratch).'": "body: 'رطوبة جدة المرتفعة (80%+) والرذاذ الملحي البحري يسرّعان تآكل الطلاء بشكل ملحوظ — خاصة في أحياء الشاطئ والخالدية والزهراء. الملح يسبب بقع تآكل دقيقة (Pitting) في الطلاء خلال 12-18 شهراً بدون حماية. الحل الأمثل هو الجمع: PPF على المناطق المعرضة (الكابوت، الرفارف الأمامية، المرايا الجانبية) + Ceramic Coating على باقي السيارة. التكلفة الإجمالية: 4,000-8,000 ريال — لكنها أرخص بكثير من إصلاح خدش واحد في طلاء سيارة فارهة (800-2,000 ريال لكل خدش).'",
        "authorEn: 'Eng. Ahmed Salem'": "author: 'م. أحمد سالم'",
        "roleEn: 'Car Protection Consultant — AzelCore'": "role: 'مستشار حماية السيارات — عزل كور'",
        "textEn: 'I advise anyone owning a luxury car in Jeddah to install PPF on the hood and front fenders at a minimum. The cost of PPF for these areas (2,500 SAR) is less than repairing two deep scratches on BMW or Mercedes paint. The sea salt in Jeddah\\'s air is a silent enemy to your car\\'s paint.'": "text: 'أنصح كل من يملك سيارة فارهة في جدة بتركيب PPF على الكابوت والرفارف الأمامية كحد أدنى. تكلفة الـ PPF لهذه المناطق (2,500 ريال) أقل من تكلفة إصلاح خدشين عميقين في طلاء BMW أو Mercedes. الملح البحري في هواء جدة عدوّ صامت لطلاء سيارتك.'",
        "qEn: 'Can PPF be installed over Ceramic Coating or vice versa?'": "q: 'هل يمكن تركيب PPF فوق Ceramic Coating أو العكس؟'",
        "aEn: 'The correct order: PPF first, then Ceramic Coating on top. This physically protects the paint with PPF and adds a layer of gloss and cleanliness above it. Installing PPF over Ceramic weakens the PPF adhesion.'": "a: 'الترتيب الصحيح: PPF أولاً ثم Ceramic Coating فوقه. هذا يحمي الطلاء فيزيائياً بالـ PPF ويضيف طبقة لمعان ونظافة فوقه. تركيب PPF فوق الـ Ceramic يضعف التصاق الـ PPF.'",
        "qEn: 'Is PPF affected by Jeddah\\'s extreme heat?'": "q: 'هل PPF يتأثر بحرارة جدة الشديدة؟'",
        "aEn: 'Original PPF films (like XPEL or SunTek) are designed to withstand temperatures exceeding 80°C. Jeddah\\'s heat won\\'t affect it. In fact, heat activates the self-healing property — any light scratch disappears when the car is exposed to the sun.'": "a: 'أفلام PPF الأصلية (مثل XPEL أو SunTek) مصممة لتحمل درجات حرارة تتجاوز 80°C. حرارة جدة لن تؤثر عليها. بل إن الحرارة تُنشّط خاصية الالتئام الذاتي — أي خدش خفيف يختفي عند تعرض السيارة للشمس.'",
        "qEn: 'How long does it take to install PPF on the hood and fenders?'": "q: 'كم يستغرق تركيب PPF للكابوت والرفارف؟'",
        "aEn: 'In a professional shop: 4-6 hours. Installation requires a clean, dust-free environment (Clean Room) and a technician with 3+ years of experience. Installing PPF is much harder than tinting and requires high skill to avoid bubbles and creases.'": "a: 'في ورشة احترافية: 4-6 ساعات. التركيب يحتاج بيئة نظيفة خالية من الغبار (Clean Room) وفنياً بخبرة 3+ سنوات. تركيب PPF أصعب بكثير من التظليل ويحتاج مهارة عالية لتجنب الفقاعات والطيّات.'",
        "warningEn: 'Installing PPF at an unspecialized shop causes bubbles and separation within weeks. Ask to see documented previous work before installing. PPF requires a technician with no less than 3 years of experience.'": "warning: 'تركيب PPF عند محل غير متخصص يسبب فقاعات وانفصالاً خلال أسابيع. اطلب رؤية أعمال سابقة مصورة قبل التركيب. PPF يحتاج فنياً بخبرة لا تقل عن 3 سنوات.'",
        "ctaEn: 'Protect your car\\'s paint from Jeddah\\'s salinity and road gravel. Free consultation with protection experts at AzelCore.'": "cta: 'احمِ طلاء سيارتك من ملوحة جدة وحصى الطرق. استشارة مجانية مع خبراء الحماية في عزل كور.'"
    },
    'src/data/blog-content/tint-signal-interference.ts': {
        "textEn: 'Nano-Ceramic Tint — Zero Signal Interference'": "text: 'تظليل نانو سيراميك — صفر تداخل مع الإشارات'",
        "textEn: 'Johnson Films — 100% Metal-Free'": "text: 'أفلام جونسون — خالية من المعادن بنسبة 100%'",
        "textEn: '3M Films — Fully Non-Metallic Technology'": "text: 'أفلام 3M — تقنية غير معدنية بالكامل'",
        "quickAnswerEn: 'Metalized tint blocks 20-60% of mobile, GPS, and Bluetooth signals because it acts as a Faraday cage. Nano-ceramic and carbon tints do not block any signals as they are 100% metal-free. In the 5G network era, choosing a metal-free film has become a necessity.'": "quickAnswer: 'التظليل المعدني (Metalized) يحجب 20-60% من إشارات الجوال وGPS وBluetooth لأنه يعمل كقفص فاراداي. التظليل النانو سيراميك والكربوني لا يحجبان أي إشارة لأنهما خاليان من المعادن 100%. في عصر شبكات 5G، اختيار فيلم خالٍ من المعادن أصبح ضرورة.'",
        "introEn: 'The most common question among our customers: \"Does tint weaken mobile signals?\" The answer depends entirely on the film type used. Older Metalized films contain aluminum or nickel particles that literally act as a barrier to electromagnetic waves (Faraday cage principle). Meanwhile, modern nano-ceramic films block heat exceptionally without any impact on communications. Here is the full engineering explanation with numbers.'": "intro: 'السؤال الأكثر شيوعاً بين عملائنا: \"هل التظليل يضعف إشارة الجوال؟\" الجواب يعتمد كلياً على نوع الفيلم المستخدم. الأفلام المعدنية القديمة (Metalized) تحتوي جزيئات ألومنيوم أو نيكل تعمل حرفياً كحاجز للموجات الكهرومغناطيسية (مبدأ قفص فاراداي). بينما أفلام النانو سيراميك الحديثة تحجب الحرارة بشكل استثنائي دون أي تأثير على الاتصالات. إليك الشرح الهندسي الكامل بالأرقام.'",
        "headersEn: ['Film Type', 'Metal Content', 'Impact on 4G/5G', 'Impact on GPS', 'Impact on Bluetooth/NFC']": "headers: ['نوع الفيلم', 'محتوى معدني', 'تأثير على 4G/5G', 'تأثير على GPS', 'تأثير على Bluetooth/NFC']",
        "rowsEn: [\n        ['Nano-Ceramic (Johnson, 3M, XPEL)', '0% (Completely free)', 'None ✅', 'None ✅', 'None ✅'],\n        ['Advanced Carbon', '0%', 'None ✅', 'None ✅', 'None ✅'],\n        ['Regular Dyed', '0%', 'None ✅', 'None ✅', 'None ✅'],\n        ['Single Metalized', '15% - 25%', '20-40% Weakness ⚠️', 'Noticeable Delay ⚠️', 'May be affected ⚠️'],\n        ['Dual Metal', '30% - 50%', '40-60% Weakness ❌', 'Frequent Loss ❌', 'Often Doesn\\'t Work ❌']\n      ]": "rows: [\n        ['نانو سيراميك (Johnson, 3M, XPEL)', '0% (خالي تماماً)', 'لا يوجد ✅', 'لا يوجد ✅', 'لا يوجد ✅'],\n        ['كربوني متقدم (Carbon)', '0%', 'لا يوجد ✅', 'لا يوجد ✅', 'لا يوجد ✅'],\n        ['مصبوغ عادي (Dyed)', '0%', 'لا يوجد ✅', 'لا يوجد ✅', 'لا يوجد ✅'],\n        ['معدني مفرد (Metalized)', '15% - 25%', 'ضعف 20-40% ⚠️', 'تأخير ملحوظ ⚠️', 'قد يتأثر ⚠️'],\n        ['معدني مزدوج (Dual Metal)', '30% - 50%', 'ضعف 40-60% ❌', 'فقدان متكرر ❌', 'لا يعمل غالباً ❌'],\n      ]",
        "headingEn: 'Why is Nano-Ceramic Completely Transparent to Signals?'": "heading: 'لماذا النانو سيراميك شفاف للإشارات تماماً؟'",
        "bodyEn: 'Nano-ceramic uses ceramic particles (Titanium Nitride or Zirconium Oxide) instead of metals. These particles are designed to absorb and scatter infrared rays (heat) but are completely transparent to the radio waves on which mobile networks (700MHz-6GHz), GPS (1.5GHz), Bluetooth (2.4GHz), and NFC operate. The equation: 97% heat block + 0% signal block.'": "body: 'النانو سيراميك يستخدم جزيئات سيراميكية (Titanium Nitride أو Zirconium Oxide) بدلاً من المعادن. هذه الجزيئات مصممة لامتصاص وتشتيت الأشعة تحت الحمراء (الحرارة) لكنها شفافة تماماً للموجات الراديوية التي تعمل عليها شبكات الجوال (700MHz-6GHz) وGPS (1.5GHz) وBluetooth (2.4GHz) وNFC. المعادلة: 97% حجب حرارة + 0% حجب إشارات.'",
        "headingEn: 'Critical Compatibility with 5G Networks in Saudi Arabia'": "heading: 'التوافق الحرج مع شبكات 5G في السعودية'",
        "bodyEn: '5G mmWave networks operate at very high frequencies (24-39 GHz). These frequencies are far more sensitive to metallic barriers than 4G networks. A metalized film blocks 60-80% of the 5G mmWave signal — meaning very slow internet speeds inside the car. With STC and Mobily expanding 5G networks in Jeddah and Riyadh, choosing a metal-free film has become a necessary technical decision, not an option.'": "body: 'شبكات 5G mmWave تعمل على ترددات عالية جداً (24-39 GHz). هذه الترددات أكثر حساسية بكثير للحواجز المعدنية من شبكات 4G. فيلم معدني يحجب 60-80% من إشارة 5G mmWave — مما يعني سرعات إنترنت بطيئة جداً داخل السيارة. مع توسع STC وMobily في نشر شبكات 5G في جدة والرياض، أصبح اختيار فيلم خالي من المعادن قراراً تقنياً ضرورياً وليس اختيارياً.'",
        "headingEn: 'How to Test Your Current Film Yourself'": "heading: 'كيف تفحص فيلمك الحالي بنفسك'",
        "bodyEn: 'Before tinting: Enter phone settings and save the signal strength in dBm (Settings > About Phone > Network Status). After tinting: Measure again in the same location. Acceptable difference: 0-3 dBm (normal). If it exceeds 5 dBm = film contains metals. Second test: Place a light magnet on the film — if it sticks or you feel slight resistance = metalized film.'": "body: 'قبل التظليل: ادخل إعدادات الهاتف واحفظ قوة الإشارة بوحدة dBm (الإعدادات > عن الهاتف > حالة الشبكة). بعد التظليل: قِس مرة أخرى في نفس المكان. الفرق المقبول: 0-3 dBm (طبيعي). إذا تجاوز 5 dBm = الفيلم يحتوي معادن. اختبار ثانٍ: ضع مغناطيساً خفيفاً على الفيلم — إذا التصق أو شعرت بمقاومة خفيفة = فيلم معدني.'",
        "authorEn: 'Eng. Ahmed Salem'": "author: 'م. أحمد سالم'",
        "roleEn: 'Thermal Insulation Consultant — AzelCore'": "role: 'مستشار العزل الحراري — عزل كور'",
        "textEn: 'With the spread of Smart Keys, keyless entry systems, and remote car unlocking apps, signal interference has become a real issue. Some customers came to us to remove metalized tint because their smart key stopped working from inside the cabin. Nano-ceramic radically solves this problem.'": "text: 'مع انتشار المفاتيح الذكية (Smart Key) وأنظمة الدخول بدون لمس وتطبيقات فتح السيارة عن بُعد، أصبح التداخل مع الإشارات مشكلة حقيقية. بعض العملاء جاؤونا لإزالة تظليل معدني لأن مفتاح السيارة الذكي توقف عن العمل من داخل المقصورة. النانو سيراميك يحل هذه المشكلة جذرياً.'",
        "qEn: 'Does carbon tint affect mobile signals?'": "q: 'هل التظليل الكربوني يؤثر على إشارة الجوال؟'",
        "aEn: 'No. Carbon is completely metal-free just like nano-ceramic. Carbon fibers do not interact with radio waves.'": "a: 'لا. الكربوني خالٍ من المعادن تماماً مثل النانو سيراميك. ألياف الكربون لا تتفاعل مع الموجات الراديوية.'",
        "qEn: 'My car is tinted and mobile signal is weak — how can I confirm the tint is the cause?'": "q: 'سيارتي فيها تظليل وإشارة الجوال ضعيفة — كيف أتأكد أن السبب هو التظليل؟'",
        "aEn: 'Test the signal strength with an open window then closed in the same location. If the signal significantly improves when the window is open = your film is metalized. Solution: remove metalized and install nano-ceramic.'": "a: 'اختبر قوة الإشارة مع نافذة مفتوحة ثم مغلقة في نفس الموقع. إذا تحسنت الإشارة بشكل ملحوظ عند فتح النافذة = فيلمك معدني. الحل: إزالة المعدني وتركيب نانو سيراميك.'",
        "qEn: 'Why do some shops still use metalized films?'": "q: 'لماذا بعض المحلات لا تزال تستخدم الأفلام المعدنية؟'",
        "aEn: 'Because they are much cheaper in cost (metalized film costs the merchant 30-50 SAR per roll versus 200-400 SAR for nano-ceramic). Some shops sell it as \"nano\" to achieve a high profit margin.'": "a: 'لأنها أرخص بكثير في التكلفة (الفيلم المعدني يكلف التاجر 30-50 ريالاً للرول مقابل 200-400 ريال للنانو سيراميك). بعض المحلات تبيعه على أنه \"نانو\" لتحقيق هامش ربح عالٍ.'",
        "warningEn: 'Some shops sell a \"nano-ceramic\" film that is actually a metal blend. Ask for the Datasheet and ensure the \"Metallic Content\" = 0%. Any metal percentage, no matter how small = signal interference.'": "warning: 'بعض المحلات تبيع فيلماً \"نانو سيراميك\" لكنه في الحقيقة معدني مخلوط. اطلب ورقة المواصفات (Datasheet) وتأكد أن خانة \"Metallic Content\" = 0%. أي نسبة معدن مهما كانت ضئيلة = حجب إشارات.'",
        "ctaEn: 'Want a tint with maximum heat rejection and zero 5G signal interference? Contact AzelCore in Jeddah.'": "cta: 'تريد تظليلاً بأقصى حجب حراري وصفر تداخل مع إشارات 5G؟ تواصل مع عزل كور بجدة.'"
    },
    'src/data/blog-content/vision-2030-energy-efficiency.ts': {
        "textEn: 'Building Glass Insulation Compliant with SBC 601 — Jeddah'": "text: 'عزل زجاج مباني متوافق مع SBC 601 — جدة'",
        "textEn: 'Certified Johnson Commercial Thermal Insulation Films'": "text: 'أفلام جونسون التجارية للعزل الحراري المعتمدة'",
        "quickAnswerEn: 'Vision 2030 aims to reduce energy consumption by 30% by 2030. Buildings consume 70% of Saudi Arabia\\'s electricity — and windows are the weakest insulation point. The SBC 601 building code requires an SHGC coefficient not exceeding 0.25 in Jeddah. Insulating glass with nano-ceramic films achieves 0.15-0.22 SHGC and saves 35-40% on AC bills.'": "quickAnswer: 'رؤية 2030 تستهدف تقليل استهلاك الطاقة 30% بحلول 2030. المباني تستهلك 70% من كهرباء السعودية — والنوافذ هي أضعف نقطة عزل. كود البناء SBC 601 يشترط معامل SHGC لا يتجاوز 0.25 في جدة. عزل الزجاج بأفلام نانو سيراميك يحقق SHGC 0.15-0.22 ويوفر 35-40% من فاتورة التكييف.'",
        "introEn: 'Saudi Arabia\\'s Vision 2030 places energy efficiency at the forefront of its economic and environmental priorities. Buildings consume roughly 70% of the total electricity produced in the Kingdom, and glass windows are the weakest link in any building\\'s thermal insulation system. The Saudi Energy Efficiency Center (SEEC) has set strict standards for new and existing buildings via the SBC 601/602 building code. In this guide, we explain how glass insulation contributes to achieving these national goals — with actual savings calculations.'": "intro: 'رؤية المملكة العربية السعودية 2030 تضع كفاءة الطاقة في صدارة أولوياتها الاقتصادية والبيئية. المباني تستهلك ما يقارب 70% من إجمالي الكهرباء المنتجة في المملكة، والنوافذ الزجاجية هي الحلقة الأضعف في منظومة العزل الحراري لأي مبنى. المركز السعودي لكفاءة الطاقة (كفاءة) وضع معايير صارمة للمباني الجديدة والقائمة عبر كود البناء SBC 601/602. في هذا الدليل، نوضح كيف يساهم عزل الزجاج في تحقيق هذه الأهداف الوطنية — مع حسابات التوفير الفعلية.'",
        "headersEn: ['Standard / Program', 'Target', 'Role of Glass Insulation', 'Financial Impact']": "headers: ['المعيار / البرنامج', 'الهدف', 'دور عزل الزجاج', 'الأثر المالي']",
        "rowsEn: [\n        ['SBC 601 Code (New Buildings)', 'SHGC ≤ 0.25', 'Film achieves 0.15-0.22 ✅', 'Prerequisite for construction permit'],\n        ['SBC 602 Code (Existing Buildings)', 'Improve energy efficiency', 'Fastest solution without breaking', 'Saves 35-40% electricity'],\n        ['\"Kafa\\'ah\" National Program', 'Reduce 30% consumption by 2030', 'Directly reduces AC load', '10,000+ SAR annual home savings'],\n        ['Green LEED Certification', '3-7 points in Energy & Atmosphere', 'Core evaluation standard', 'Raises rental value 15-25%']\n      ]": "rows: [\n        ['كود SBC 601 (مباني جديدة)', 'SHGC ≤ 0.25', 'الفيلم يحقق 0.15-0.22 ✅', 'شرط لإصدار رخصة الإنشاء'],\n        ['كود SBC 602 (مباني قائمة)', 'تحسين كفاءة الطاقة', 'أسرع حل بدون تكسير', 'توفير 35-40% كهرباء'],\n        ['برنامج \"كفاءة\" الوطني', 'تقليل 30% استهلاك بحلول 2030', 'يقلل حمل التكييف مباشرة', '10,000+ ر.س توفير سنوي للمنزل'],\n        ['شهادة LEED الخضراء', '3-7 نقاط في Energy & Atmosphere', 'معيار أساسي للتقييم', 'ترفع قيمة الإيجار 15-25%'],\n      ]",
        "headingEn: 'Saudi Building Code SBC 601: What You Must Know'": "heading: 'كود البناء السعودي SBC 601: ما يجب أن تعرفه'",
        "bodyEn: 'The SBC 601 code mandates all new buildings in Climate Zone 1 (including Jeddah, Mecca, Taif) that the window Solar Heat Gain Coefficient (SHGC) must not cross the 0.25 barrier. Regular uninsulated glass scores between 0.70 and 0.82 — failing miserably. Nano-ceramic thermal insulation films achieve an SHGC between 0.15 and 0.22 — completely compliant with the code without needing glass replacement. Existing buildings that add glass insulation meet SBC 602 requirements for renovation and energy savings.'": "body: 'كود SBC 601 يُلزم جميع المباني الجديدة في المنطقة المناخية 1 (تشمل جدة ومكة والطائف) بألا يتجاوز معامل الكسب الحراري الشمسي (SHGC) للزجاج حاجز 0.25. الزجاج العادي بدون عزل يسجل SHGC بين 0.70 و 0.82 — أي أنه يفشل فشلاً ذريعاً. أفلام العزل الحراري النانو سيراميك تحقق SHGC بين 0.15 و 0.22 — مطابقة تماماً للكود وبدون الحاجة لتغيير الزجاج. المباني القائمة التي تضيف عزل الزجاج تحقق متطلبات SBC 602 للترميم وتوفير الطاقة.'",
        "headingEn: 'Real Savings: Numbers from Completed Projects'": "heading: 'التوفير الحقيقي: أرقام من مشاريع منفذة'",
        "bodyEn: 'A villa in Al-Safa district, Jeddah (300m²): The bill dropped from 3,200 to 1,800 SAR monthly — 44% savings. A 5-story office building with glass facade: 230,000 SAR annual savings. Commercial showroom: Recovered insulation cost in just 11 months (ROI). Public school: 35% savings + added safety for students via glass cohesion if broken. Windows facing west and south transfer 60% of heat — start with them first for maximum return.'": "body: 'فيلا في حي الصفا بجدة (300م²): الفاتورة انخفضت من 3,200 إلى 1,800 ريال شهرياً — توفير 44%. مبنى مكاتب 5 أدوار بواجهة زجاجية: توفير 230,000 ريال سنوياً. معرض تجاري: استرداد تكلفة العزل خلال 11 شهراً فقط (ROI). مدرسة حكومية: توفير 35% + حماية أمان إضافية للطلاب عبر تماسك الزجاج في حال الكسر. النوافذ المطلة على الواجهة الغربية والجنوبية تنقل 60% من الحرارة — ابدأ بها أولاً لأقصى عائد.'",
        "headingEn: 'LEED Certification and Property Value'": "heading: 'شهادة LEED وقيمة العقار'",
        "bodyEn: 'A building with a Green LEED certification sees its rental value increase by 15-25% in the Saudi market. Glass insulation grants 3-7 points in the \"Energy & Atmosphere\" category and is one of the easiest to achieve. Modern real estate valuation calculates energy efficiency as a core factor in estimating building value. In Jeddah specifically: insulated commercial buildings are leased 40% faster than uninsulated ones because tenants look for lower electricity bills.'": "body: 'المبنى الحاصل على شهادة LEED الخضراء ترتفع قيمته الإيجارية بنسبة 15-25% في السوق السعودي. عزل الزجاج يمنح 3-7 نقاط في معيار \"Energy & Atmosphere\" وهو من أسهل النقاط تحقيقاً. التقييم العقاري الحديث يحسب كفاءة الطاقة كعامل أساسي في تقدير قيمة المبنى. في جدة تحديداً: المباني التجارية المعزولة تُؤجر أسرع بنسبة 40% من المباني غير المعزولة لأن المستأجرين يبحثون عن فواتير كهرباء أقل.'",
        "authorEn: 'Projects Team — AzelCore'": "author: 'فريق المشاريع — عزل كور'",
        "roleEn: 'Commercial Buildings & Facilities Insulation Dept.'": "role: 'قسم عزل المباني والمنشآت التجارية'",
        "textEn: 'We provide every commercial client with a detailed report calculating the Return on Investment (ROI) before execution, including: current bill, expected savings in SAR, and cost recovery period. In 90% of cases, the owner recovers the insulation cost during the first summer. This is not an expense — this is a guaranteed return investment.'": "text: 'نحن نقدم لكل عميل تجاري تقريراً مفصلاً يحسب العائد على الاستثمار (ROI) قبل التنفيذ، يتضمن: الفاتورة الحالية، التوفير المتوقع بالريال، ومدة استرداد التكلفة. في 90% من الحالات، يسترد المالك تكلفة العزل خلال أول صيف. هذا ليس إنفاقاً — هذا استثمار بعائد مضمون.'",
        "qEn: 'Is glass insulation mandatory in new buildings?'": "q: 'هل عزل الزجاج إلزامي في المباني الجديدة؟'",
        "aEn: 'Yes. The Saudi Building Code SBC 601 mandates new buildings to achieve specific glass insulation standards (SHGC ≤ 0.25). Buildings that fail to comply may face delays in operating permits and fines.'": "a: 'نعم. كود البناء السعودي SBC 601 يُلزم المباني الجديدة بتحقيق معايير عزل محددة للزجاج (SHGC ≤ 0.25). المباني التي لا تلتزم قد تواجه تأخيراً في إصدار رخص التشغيل وغرامات.'",
        "qEn: 'How does glass insulation help in getting LEED certification?'": "q: 'كيف يساعد عزل الزجاج في الحصول على شهادة LEED؟'",
        "aEn: 'Glass insulation grants the building 3-7 points in the Energy & Atmosphere category within the LEED evaluation. It is one of the fastest solutions to implement and lowest in cost compared to changing AC systems or structural insulation.'": "a: 'عزل الزجاج يمنح المبنى 3-7 نقاط في فئة Energy & Atmosphere ضمن تقييم LEED. وهو من أسرع الحلول تنفيذاً وأقلها تكلفة مقارنة بتغيير أنظمة التكييف أو العزل الإنشائي.'",
        "qEn: 'Is there government support for insulating existing buildings?'": "q: 'هل يوجد دعم حكومي لعزل المباني القائمة؟'",
        "aEn: 'The \"Kafa\\'ah\" program supports energy-saving solutions. Some city municipalities provide facilities for buildings complying with SBC 601 standards. Commercial building insurance is cheaper with an energy efficiency certificate.'": "a: 'برنامج \"كفاءة\" يدعم حلول توفير الطاقة. بعض أمانات المدن تقدم تسهيلات للمباني الملتزمة بمعايير SBC 601. التأمين على المباني التجارية يكون أرخص مع وجود شهادة كفاءة الطاقة.'",
        "warningEn: 'Buildings non-compliant with SBC 601 standards after 2025 may face financial fines and delays in issuing and renewing operating permits. Glass film insulation is the fastest and cheapest way to comply — without breaking or halting building activity.'": "warning: 'المباني غير الملتزمة بمعايير SBC 601 بعد 2025 قد تواجه غرامات مالية وتأخيراً في إصدار رخص التشغيل والتجديد. عزل الزجاج بالفيلم هو أسرع وأرخص طريقة للامتثال — بدون تكسير أو إيقاف نشاط المبنى.'",
        "ctaEn: 'Contribute to Vision 2030 goals and save thousands of Riyals. Get a free thermal assessment for your building from AzelCore experts.'": "cta: 'ساهم في أهداف رؤية 2030 ووفّر آلاف الريالات. احصل على تقييم حراري مجاني لمبناك من خبراء عزل كور.'"
    }
}

for file_path, replacements in files_data.items():
    try:
        with open(file_path, 'r', encoding='utf-8') as f:
            content = f.read()
            
        for eng_str, ar_str in replacements.items():
            if ar_str in content:
                content = content.replace(ar_str, f"{ar_str}, {eng_str}")
                
        with open(file_path, 'w', encoding='utf-8') as f:
            f.write(content)
            
        print(f"Updated {file_path}")
    except Exception as e:
        print(f"Error on {file_path}: {e}")
